// Copyright 2026 ScitiX
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: sandbox/ctrlplane/v1/ctrlplane.proto

package ctrlplanev1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_PushRoute_FullMethodName     = "/sandbox.ctrlplane.v1.ControlPlaneService/PushRoute"
	ControlPlaneService_EvictRoute_FullMethodName    = "/sandbox.ctrlplane.v1.ControlPlaneService/EvictRoute"
	ControlPlaneService_GetLastActive_FullMethodName = "/sandbox.ctrlplane.v1.ControlPlaneService/GetLastActive"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlaneService is the private RPC channel between the Controller and
// the ExtProc gateway. It is NOT exposed to end users; the server binds to an
// in-cluster port and authenticates callers with the shared admin key.
type ControlPlaneServiceClient interface {
	// PushRoute registers a sandbox_id -> (namespace, pod_name) mapping in the
	// ExtProc in-memory cache so router queries can bypass the informer's
	// sandbox-id index. The mapping carries NO phase and NO PodIP: those are
	// read live from the Pod informer on each request, so the cache never goes
	// stale across Pod lifecycle transitions (Starting -> Running -> Stopping).
	PushRoute(ctx context.Context, in *PushRouteRequest, opts ...grpc.CallOption) (*PushRouteResponse, error)
	// EvictRoute removes a sandbox_id from the ExtProc cache. Called by the
	// Controller when a Pod completes Stopping -> Idle, so subsequent router
	// queries for the released sandbox_id fall through to "not found" instead
	// of briefly hitting a stale cache entry.
	EvictRoute(ctx context.Context, in *EvictRouteRequest, opts ...grpc.CallOption) (*EvictRouteResponse, error)
	// GetLastActive returns the per-sandbox last-activity timestamps tracked
	// by ExtProc. Used by the Controller's IdleTimeoutReconciler.
	GetLastActive(ctx context.Context, in *GetLastActiveRequest, opts ...grpc.CallOption) (*GetLastActiveResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) PushRoute(ctx context.Context, in *PushRouteRequest, opts ...grpc.CallOption) (*PushRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushRouteResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_PushRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) EvictRoute(ctx context.Context, in *EvictRouteRequest, opts ...grpc.CallOption) (*EvictRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvictRouteResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_EvictRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneServiceClient) GetLastActive(ctx context.Context, in *GetLastActiveRequest, opts ...grpc.CallOption) (*GetLastActiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastActiveResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetLastActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// ControlPlaneService is the private RPC channel between the Controller and
// the ExtProc gateway. It is NOT exposed to end users; the server binds to an
// in-cluster port and authenticates callers with the shared admin key.
type ControlPlaneServiceServer interface {
	// PushRoute registers a sandbox_id -> (namespace, pod_name) mapping in the
	// ExtProc in-memory cache so router queries can bypass the informer's
	// sandbox-id index. The mapping carries NO phase and NO PodIP: those are
	// read live from the Pod informer on each request, so the cache never goes
	// stale across Pod lifecycle transitions (Starting -> Running -> Stopping).
	PushRoute(context.Context, *PushRouteRequest) (*PushRouteResponse, error)
	// EvictRoute removes a sandbox_id from the ExtProc cache. Called by the
	// Controller when a Pod completes Stopping -> Idle, so subsequent router
	// queries for the released sandbox_id fall through to "not found" instead
	// of briefly hitting a stale cache entry.
	EvictRoute(context.Context, *EvictRouteRequest) (*EvictRouteResponse, error)
	// GetLastActive returns the per-sandbox last-activity timestamps tracked
	// by ExtProc. Used by the Controller's IdleTimeoutReconciler.
	GetLastActive(context.Context, *GetLastActiveRequest) (*GetLastActiveResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) PushRoute(context.Context, *PushRouteRequest) (*PushRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushRoute not implemented")
}
func (UnimplementedControlPlaneServiceServer) EvictRoute(context.Context, *EvictRouteRequest) (*EvictRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvictRoute not implemented")
}
func (UnimplementedControlPlaneServiceServer) GetLastActive(context.Context, *GetLastActiveRequest) (*GetLastActiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastActive not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_PushRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).PushRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_PushRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).PushRoute(ctx, req.(*PushRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_EvictRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvictRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).EvictRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_EvictRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).EvictRoute(ctx, req.(*EvictRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneService_GetLastActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastActiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetLastActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetLastActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetLastActive(ctx, req.(*GetLastActiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.ctrlplane.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushRoute",
			Handler:    _ControlPlaneService_PushRoute_Handler,
		},
		{
			MethodName: "EvictRoute",
			Handler:    _ControlPlaneService_EvictRoute_Handler,
		},
		{
			MethodName: "GetLastActive",
			Handler:    _ControlPlaneService_GetLastActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox/ctrlplane/v1/ctrlplane.proto",
}
