/**
 * Copyright 2026 ScitiX
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Kubernetes Resource Quantity Parsing Utilities
 * * CPU    -> Number of cores (e.g., "8000m" -> 8, "0.5" -> 0.5)
 * * Memory -> Value in MiB (e.g., "1Gi" -> 1024, "512Mi" -> 512, "1048576" -> 1)
 */

// ---------------------------------------------------------------------------
// CPU Parsing (returns the number of cores)
// ---------------------------------------------------------------------------

const CPU_MILLICORE_REGEX = /^([0-9]*\.?[0-9]+)\s*m$/i

export function parseCpuToCore(raw: string | null | undefined): number | undefined {
  if (raw == null || raw === "") return undefined
  const trimmed = raw.trim()

  const milliMatch = trimmed.match(CPU_MILLICORE_REGEX)
  if (milliMatch) {
    return parseFloat(milliMatch[1]) / 1000
  }

  const n = Number(trimmed)
  return isNaN(n) ? undefined : n
}

// ---------------------------------------------------------------------------
// Memory Parsing (converted to MiB)
// ---------------------------------------------------------------------------

const MiB_BYTES = 1024 ** 2 // 1,048,576 bytes

const BINARY_UNITS: Record<string, number> = {
  Ki: 1024,
  Mi: 1024 ** 2,
  Gi: 1024 ** 3,
  Ti: 1024 ** 4,
  Pi: 1024 ** 5,
  Ei: 1024 ** 6,
}

const SI_UNITS: Record<string, number> = {
  k: 1e3,
  K: 1e3,
  M: 1e6,
  G: 1e9,
  T: 1e12,
  P: 1e15,
  E: 1e18,
}

// Matches: <Number><Optional Unit>
const MEMORY_REGEX = /^([0-9]*\.?[0-9]+)\s*(Ki|Mi|Gi|Ti|Pi|Ei|k|K|M|G|T|P|E|m)?$/

/**
 * Parses a K8s memory string and returns the value in MiB.
 * * Examples:
 * - "1Gi"    -> 1024
 * - "512Mi"  -> 512
 * - "1024Ki" -> 1
 * - "1G"     -> 953.67 (10^9 / 1024^2)
 */
export function parseMemoryToMiB(raw: string | null | undefined): number | undefined {
  if (raw == null || raw === "") return undefined
  const trimmed = raw.trim()

  const match = trimmed.match(MEMORY_REGEX)
  if (!match) return undefined

  const value = parseFloat(match[1])
  const suffix = match[2] ?? ""

  let bytes: number

  if (suffix === "") {
    bytes = value // Pure numbers are treated as Bytes
  } else if (suffix === "m") {
    bytes = value / 1000 // milli-bytes
  } else if (suffix in BINARY_UNITS) {
    bytes = value * BINARY_UNITS[suffix]
  } else if (suffix in SI_UNITS) {
    bytes = value * SI_UNITS[suffix]
  } else {
    return undefined
  }

  return bytes / MiB_BYTES
}

// ---------------------------------------------------------------------------
// Display Helper Functions
// ---------------------------------------------------------------------------

/**
 * Formats the MiB value for frontend display.
 * - Integers are displayed directly (e.g., "1024").
 * - Decimals are rounded to 2 decimal places (e.g., "512.25").
 */
export function formatMiB(mib: number): string {
  if (Number.isInteger(mib)) return `${mib}`
  // Using parseFloat again to remove trailing zeros generated by toFixed()
  return parseFloat(mib.toFixed(2)).toString()
}

/**
 * Formats CPU cores.
 */
export function formatCores(cores: number): string {
  if (Number.isInteger(cores)) return `${cores}`
  return parseFloat(cores.toFixed(3)).toString()
}

// ---------------------------------------------------------------------------
// Unit-aware form input
//
// Resource forms take a whole number plus a unit, so a Pod can be sized in
// milli-cores / MiB as well as whole cores / GiB. Milli-cores and MiB are the
// comparison basis throughout: comparing in whole cores instead would floor a
// 20m request to 0 (or round it up to a whole core) and misjudge limits.
// ---------------------------------------------------------------------------

export type CpuUnit = "core" | "milli"
export type MemoryUnit = "Gi" | "Mi"

/** Converts a form amount + unit into milli-cores. */
export function toMilliCores(
  value: number | string | undefined,
  unit: CpuUnit,
): number | undefined {
  if (value === undefined || value === "") return undefined
  const n = Number(value)
  if (!Number.isFinite(n)) return undefined
  return unit === "milli" ? n : n * 1000
}

/** Converts a form amount + unit into MiB. */
export function toMiB(value: number | string | undefined, unit: MemoryUnit): number | undefined {
  if (value === undefined || value === "") return undefined
  const n = Number(value)
  if (!Number.isFinite(n)) return undefined
  return unit === "Mi" ? n : n * 1024
}

/** Renders a form amount + unit as a Kubernetes CPU Quantity ("2", "20m"). */
export function cpuQuantity(value: number, unit: CpuUnit): string {
  return unit === "milli" ? `${value}m` : String(value)
}

/** Renders a form amount + unit as a Kubernetes memory Quantity ("8Gi", "128Mi"). */
export function memoryQuantity(value: number, unit: MemoryUnit): string {
  return `${value}${unit}`
}

/**
 * Picks the unit that renders the amount as a whole number, so a Pool created
 * with 20m reopens showing "20 millicores" rather than a rounded-off "1 core".
 */
export function splitCpu(cores: number): { value: number; unit: CpuUnit } {
  const milli = Math.round(cores * 1000)
  if (milli !== 0 && milli % 1000 === 0) return { value: milli / 1000, unit: "core" }
  return { value: milli, unit: "milli" }
}

/** Memory counterpart of splitCpu: whole GiB stays GiB, anything else is MiB. */
export function splitMemory(mib: number): { value: number; unit: MemoryUnit } {
  const rounded = Math.round(mib)
  if (rounded !== 0 && rounded % 1024 === 0) return { value: rounded / 1024, unit: "Gi" }
  return { value: rounded, unit: "Mi" }
}
