apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-sandbox-worker.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-sandbox-worker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "agent-sandbox-worker.controllerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        {{- include "agent-sandbox-worker.controllerSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: manager
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          command:
            - /sandbox
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --extproc-internal-api-url={{ include "agent-sandbox-worker.extprocInternalApiUrl" . }}
            - --envoy-gateway-base-url={{ include "agent-sandbox-worker.envoyGatewayBaseUrl" . }}
            - --e2b-bind-address=:8090
            - --e2b-domain={{ include "agent-sandbox-worker.e2bDomain" . }}
          env:
            - name: LOCAL_CLUSTER_ID
              value: {{ .Values.controller.localClusterId | quote }}
          envFrom:
            - secretRef:
                name: {{ include "agent-sandbox-worker.secretName" . }}
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
            - containerPort: 8090
              name: e2b-api
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: {{ include "agent-sandbox-worker.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
      {{- with .Values.controller.nodeAffinity }}
      affinity:
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
