{{- if and .Values.extproc.podDisruptionBudget.enabled (gt (int .Values.extproc.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "agent-sandbox-worker.fullname" . }}-extproc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-sandbox-worker.labels" . | nindent 4 }}
    {{- include "agent-sandbox-worker.extprocSelectorLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.extproc.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "agent-sandbox-worker.extprocSelectorLabels" . | nindent 6 }}
{{- end }}
