apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-sandbox-worker.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-sandbox-worker.labels" . | nindent 4 }}
