// Copyright 2026 ScitiX
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: sandbox/sync/v1/sync.proto

package syncv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	APIKeyService_CreateKey_FullMethodName = "/sandbox.sync.v1.APIKeyService/CreateKey"
	APIKeyService_DeleteKey_FullMethodName = "/sandbox.sync.v1.APIKeyService/DeleteKey"
	APIKeyService_WatchKeys_FullMethodName = "/sandbox.sync.v1.APIKeyService/WatchKeys"
)

// APIKeyServiceClient is the client API for APIKeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIKeyServiceClient interface {
	CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error)
	DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error)
	// WatchKeys emits a KeySnapshot first (carrying every key currently held by
	// the Hub) and then a stream of Upsert/Delete events as the Hub-side store
	// changes. The Worker should re-subscribe whenever the underlying connection
	// drops; the next Snapshot is the authoritative truth.
	WatchKeys(ctx context.Context, in *WatchKeysRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KeyEvent], error)
}

type aPIKeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIKeyServiceClient(cc grpc.ClientConnInterface) APIKeyServiceClient {
	return &aPIKeyServiceClient{cc}
}

func (c *aPIKeyServiceClient) CreateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*CreateKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyResponse)
	err := c.cc.Invoke(ctx, APIKeyService_CreateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeyServiceClient) DeleteKey(ctx context.Context, in *DeleteKeyRequest, opts ...grpc.CallOption) (*DeleteKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyResponse)
	err := c.cc.Invoke(ctx, APIKeyService_DeleteKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIKeyServiceClient) WatchKeys(ctx context.Context, in *WatchKeysRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KeyEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &APIKeyService_ServiceDesc.Streams[0], APIKeyService_WatchKeys_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchKeysRequest, KeyEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type APIKeyService_WatchKeysClient = grpc.ServerStreamingClient[KeyEvent]

// APIKeyServiceServer is the server API for APIKeyService service.
// All implementations must embed UnimplementedAPIKeyServiceServer
// for forward compatibility.
type APIKeyServiceServer interface {
	CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error)
	DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error)
	// WatchKeys emits a KeySnapshot first (carrying every key currently held by
	// the Hub) and then a stream of Upsert/Delete events as the Hub-side store
	// changes. The Worker should re-subscribe whenever the underlying connection
	// drops; the next Snapshot is the authoritative truth.
	WatchKeys(*WatchKeysRequest, grpc.ServerStreamingServer[KeyEvent]) error
	mustEmbedUnimplementedAPIKeyServiceServer()
}

// UnimplementedAPIKeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIKeyServiceServer struct{}

func (UnimplementedAPIKeyServiceServer) CreateKey(context.Context, *CreateKeyRequest) (*CreateKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKey not implemented")
}
func (UnimplementedAPIKeyServiceServer) DeleteKey(context.Context, *DeleteKeyRequest) (*DeleteKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKey not implemented")
}
func (UnimplementedAPIKeyServiceServer) WatchKeys(*WatchKeysRequest, grpc.ServerStreamingServer[KeyEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchKeys not implemented")
}
func (UnimplementedAPIKeyServiceServer) mustEmbedUnimplementedAPIKeyServiceServer() {}
func (UnimplementedAPIKeyServiceServer) testEmbeddedByValue()                       {}

// UnsafeAPIKeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIKeyServiceServer will
// result in compilation errors.
type UnsafeAPIKeyServiceServer interface {
	mustEmbedUnimplementedAPIKeyServiceServer()
}

func RegisterAPIKeyServiceServer(s grpc.ServiceRegistrar, srv APIKeyServiceServer) {
	// If the following call panics, it indicates UnimplementedAPIKeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APIKeyService_ServiceDesc, srv)
}

func _APIKeyService_CreateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeyServiceServer).CreateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeyService_CreateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeyServiceServer).CreateKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeyService_DeleteKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIKeyServiceServer).DeleteKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIKeyService_DeleteKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIKeyServiceServer).DeleteKey(ctx, req.(*DeleteKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIKeyService_WatchKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIKeyServiceServer).WatchKeys(m, &grpc.GenericServerStream[WatchKeysRequest, KeyEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type APIKeyService_WatchKeysServer = grpc.ServerStreamingServer[KeyEvent]

// APIKeyService_ServiceDesc is the grpc.ServiceDesc for APIKeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIKeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.sync.v1.APIKeyService",
	HandlerType: (*APIKeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKey",
			Handler:    _APIKeyService_CreateKey_Handler,
		},
		{
			MethodName: "DeleteKey",
			Handler:    _APIKeyService_DeleteKey_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchKeys",
			Handler:       _APIKeyService_WatchKeys_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandbox/sync/v1/sync.proto",
}

const (
	VaultService_PutEntry_FullMethodName     = "/sandbox.sync.v1.VaultService/PutEntry"
	VaultService_DeleteEntry_FullMethodName  = "/sandbox.sync.v1.VaultService/DeleteEntry"
	VaultService_WatchEntries_FullMethodName = "/sandbox.sync.v1.VaultService/WatchEntries"
)

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VaultServiceClient interface {
	// PutEntry creates or rotates an entry. The Hub owns the version counter, so
	// two Workers writing the same name cannot both believe they produced v2.
	PutEntry(ctx context.Context, in *PutVaultEntryRequest, opts ...grpc.CallOption) (*PutVaultEntryResponse, error)
	DeleteEntry(ctx context.Context, in *DeleteVaultEntryRequest, opts ...grpc.CallOption) (*DeleteVaultEntryResponse, error)
	// WatchEntries emits a Snapshot first, then Upsert/Delete events. The
	// Snapshot is authoritative: a Worker reconciling against it must drop local
	// entries the Hub no longer knows about, or a delete that arrived while the
	// connection was down would never take effect.
	WatchEntries(ctx context.Context, in *WatchVaultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VaultEvent], error)
}

type vaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultServiceClient(cc grpc.ClientConnInterface) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) PutEntry(ctx context.Context, in *PutVaultEntryRequest, opts ...grpc.CallOption) (*PutVaultEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutVaultEntryResponse)
	err := c.cc.Invoke(ctx, VaultService_PutEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) DeleteEntry(ctx context.Context, in *DeleteVaultEntryRequest, opts ...grpc.CallOption) (*DeleteVaultEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVaultEntryResponse)
	err := c.cc.Invoke(ctx, VaultService_DeleteEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) WatchEntries(ctx context.Context, in *WatchVaultRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VaultEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VaultService_ServiceDesc.Streams[0], VaultService_WatchEntries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchVaultRequest, VaultEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VaultService_WatchEntriesClient = grpc.ServerStreamingClient[VaultEvent]

// VaultServiceServer is the server API for VaultService service.
// All implementations must embed UnimplementedVaultServiceServer
// for forward compatibility.
type VaultServiceServer interface {
	// PutEntry creates or rotates an entry. The Hub owns the version counter, so
	// two Workers writing the same name cannot both believe they produced v2.
	PutEntry(context.Context, *PutVaultEntryRequest) (*PutVaultEntryResponse, error)
	DeleteEntry(context.Context, *DeleteVaultEntryRequest) (*DeleteVaultEntryResponse, error)
	// WatchEntries emits a Snapshot first, then Upsert/Delete events. The
	// Snapshot is authoritative: a Worker reconciling against it must drop local
	// entries the Hub no longer knows about, or a delete that arrived while the
	// connection was down would never take effect.
	WatchEntries(*WatchVaultRequest, grpc.ServerStreamingServer[VaultEvent]) error
	mustEmbedUnimplementedVaultServiceServer()
}

// UnimplementedVaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaultServiceServer struct{}

func (UnimplementedVaultServiceServer) PutEntry(context.Context, *PutVaultEntryRequest) (*PutVaultEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutEntry not implemented")
}
func (UnimplementedVaultServiceServer) DeleteEntry(context.Context, *DeleteVaultEntryRequest) (*DeleteVaultEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEntry not implemented")
}
func (UnimplementedVaultServiceServer) WatchEntries(*WatchVaultRequest, grpc.ServerStreamingServer[VaultEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchEntries not implemented")
}
func (UnimplementedVaultServiceServer) mustEmbedUnimplementedVaultServiceServer() {}
func (UnimplementedVaultServiceServer) testEmbeddedByValue()                      {}

// UnsafeVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultServiceServer will
// result in compilation errors.
type UnsafeVaultServiceServer interface {
	mustEmbedUnimplementedVaultServiceServer()
}

func RegisterVaultServiceServer(s grpc.ServiceRegistrar, srv VaultServiceServer) {
	// If the following call panics, it indicates UnimplementedVaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaultService_ServiceDesc, srv)
}

func _VaultService_PutEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVaultEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).PutEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_PutEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).PutEntry(ctx, req.(*PutVaultEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_DeleteEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVaultEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).DeleteEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_DeleteEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).DeleteEntry(ctx, req.(*DeleteVaultEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_WatchEntries_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchVaultRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VaultServiceServer).WatchEntries(m, &grpc.GenericServerStream[WatchVaultRequest, VaultEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VaultService_WatchEntriesServer = grpc.ServerStreamingServer[VaultEvent]

// VaultService_ServiceDesc is the grpc.ServiceDesc for VaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.sync.v1.VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutEntry",
			Handler:    _VaultService_PutEntry_Handler,
		},
		{
			MethodName: "DeleteEntry",
			Handler:    _VaultService_DeleteEntry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEntries",
			Handler:       _VaultService_WatchEntries_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandbox/sync/v1/sync.proto",
}

const (
	TemplateService_CreateTemplate_FullMethodName = "/sandbox.sync.v1.TemplateService/CreateTemplate"
	TemplateService_UpdateTemplate_FullMethodName = "/sandbox.sync.v1.TemplateService/UpdateTemplate"
	TemplateService_DeleteTemplate_FullMethodName = "/sandbox.sync.v1.TemplateService/DeleteTemplate"
	TemplateService_WatchTemplates_FullMethodName = "/sandbox.sync.v1.TemplateService/WatchTemplates"
)

// TemplateServiceClient is the client API for TemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplateServiceClient interface {
	CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error)
	UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error)
	DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error)
	// WatchTemplates emits a TemplateSnapshot first and then Upsert/Delete events.
	WatchTemplates(ctx context.Context, in *WatchTemplatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TemplateEvent], error)
}

type templateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplateServiceClient(cc grpc.ClientConnInterface) TemplateServiceClient {
	return &templateServiceClient{cc}
}

func (c *templateServiceClient) CreateTemplate(ctx context.Context, in *CreateTemplateRequest, opts ...grpc.CallOption) (*CreateTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTemplateResponse)
	err := c.cc.Invoke(ctx, TemplateService_CreateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) UpdateTemplate(ctx context.Context, in *UpdateTemplateRequest, opts ...grpc.CallOption) (*UpdateTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTemplateResponse)
	err := c.cc.Invoke(ctx, TemplateService_UpdateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) DeleteTemplate(ctx context.Context, in *DeleteTemplateRequest, opts ...grpc.CallOption) (*DeleteTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTemplateResponse)
	err := c.cc.Invoke(ctx, TemplateService_DeleteTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *templateServiceClient) WatchTemplates(ctx context.Context, in *WatchTemplatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TemplateEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TemplateService_ServiceDesc.Streams[0], TemplateService_WatchTemplates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTemplatesRequest, TemplateEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TemplateService_WatchTemplatesClient = grpc.ServerStreamingClient[TemplateEvent]

// TemplateServiceServer is the server API for TemplateService service.
// All implementations must embed UnimplementedTemplateServiceServer
// for forward compatibility.
type TemplateServiceServer interface {
	CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error)
	UpdateTemplate(context.Context, *UpdateTemplateRequest) (*UpdateTemplateResponse, error)
	DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error)
	// WatchTemplates emits a TemplateSnapshot first and then Upsert/Delete events.
	WatchTemplates(*WatchTemplatesRequest, grpc.ServerStreamingServer[TemplateEvent]) error
	mustEmbedUnimplementedTemplateServiceServer()
}

// UnimplementedTemplateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTemplateServiceServer struct{}

func (UnimplementedTemplateServiceServer) CreateTemplate(context.Context, *CreateTemplateRequest) (*CreateTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTemplate not implemented")
}
func (UnimplementedTemplateServiceServer) UpdateTemplate(context.Context, *UpdateTemplateRequest) (*UpdateTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTemplate not implemented")
}
func (UnimplementedTemplateServiceServer) DeleteTemplate(context.Context, *DeleteTemplateRequest) (*DeleteTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTemplate not implemented")
}
func (UnimplementedTemplateServiceServer) WatchTemplates(*WatchTemplatesRequest, grpc.ServerStreamingServer[TemplateEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchTemplates not implemented")
}
func (UnimplementedTemplateServiceServer) mustEmbedUnimplementedTemplateServiceServer() {}
func (UnimplementedTemplateServiceServer) testEmbeddedByValue()                         {}

// UnsafeTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplateServiceServer will
// result in compilation errors.
type UnsafeTemplateServiceServer interface {
	mustEmbedUnimplementedTemplateServiceServer()
}

func RegisterTemplateServiceServer(s grpc.ServiceRegistrar, srv TemplateServiceServer) {
	// If the following call panics, it indicates UnimplementedTemplateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TemplateService_ServiceDesc, srv)
}

func _TemplateService_CreateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).CreateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_CreateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).CreateTemplate(ctx, req.(*CreateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_UpdateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).UpdateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_UpdateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).UpdateTemplate(ctx, req.(*UpdateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_DeleteTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplateServiceServer).DeleteTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TemplateService_DeleteTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplateServiceServer).DeleteTemplate(ctx, req.(*DeleteTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TemplateService_WatchTemplates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTemplatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TemplateServiceServer).WatchTemplates(m, &grpc.GenericServerStream[WatchTemplatesRequest, TemplateEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TemplateService_WatchTemplatesServer = grpc.ServerStreamingServer[TemplateEvent]

// TemplateService_ServiceDesc is the grpc.ServiceDesc for TemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.sync.v1.TemplateService",
	HandlerType: (*TemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTemplate",
			Handler:    _TemplateService_CreateTemplate_Handler,
		},
		{
			MethodName: "UpdateTemplate",
			Handler:    _TemplateService_UpdateTemplate_Handler,
		},
		{
			MethodName: "DeleteTemplate",
			Handler:    _TemplateService_DeleteTemplate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTemplates",
			Handler:       _TemplateService_WatchTemplates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandbox/sync/v1/sync.proto",
}

const (
	ClusterConfigService_WatchClusterConfig_FullMethodName = "/sandbox.sync.v1.ClusterConfigService/WatchClusterConfig"
)

// ClusterConfigServiceClient is the client API for ClusterConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterConfigServiceClient interface {
	WatchClusterConfig(ctx context.Context, in *WatchClusterConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClusterConfigEvent], error)
}

type clusterConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterConfigServiceClient(cc grpc.ClientConnInterface) ClusterConfigServiceClient {
	return &clusterConfigServiceClient{cc}
}

func (c *clusterConfigServiceClient) WatchClusterConfig(ctx context.Context, in *WatchClusterConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClusterConfigEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterConfigService_ServiceDesc.Streams[0], ClusterConfigService_WatchClusterConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchClusterConfigRequest, ClusterConfigEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterConfigService_WatchClusterConfigClient = grpc.ServerStreamingClient[ClusterConfigEvent]

// ClusterConfigServiceServer is the server API for ClusterConfigService service.
// All implementations must embed UnimplementedClusterConfigServiceServer
// for forward compatibility.
type ClusterConfigServiceServer interface {
	WatchClusterConfig(*WatchClusterConfigRequest, grpc.ServerStreamingServer[ClusterConfigEvent]) error
	mustEmbedUnimplementedClusterConfigServiceServer()
}

// UnimplementedClusterConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterConfigServiceServer struct{}

func (UnimplementedClusterConfigServiceServer) WatchClusterConfig(*WatchClusterConfigRequest, grpc.ServerStreamingServer[ClusterConfigEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchClusterConfig not implemented")
}
func (UnimplementedClusterConfigServiceServer) mustEmbedUnimplementedClusterConfigServiceServer() {}
func (UnimplementedClusterConfigServiceServer) testEmbeddedByValue()                              {}

// UnsafeClusterConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterConfigServiceServer will
// result in compilation errors.
type UnsafeClusterConfigServiceServer interface {
	mustEmbedUnimplementedClusterConfigServiceServer()
}

func RegisterClusterConfigServiceServer(s grpc.ServiceRegistrar, srv ClusterConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedClusterConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterConfigService_ServiceDesc, srv)
}

func _ClusterConfigService_WatchClusterConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchClusterConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterConfigServiceServer).WatchClusterConfig(m, &grpc.GenericServerStream[WatchClusterConfigRequest, ClusterConfigEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterConfigService_WatchClusterConfigServer = grpc.ServerStreamingServer[ClusterConfigEvent]

// ClusterConfigService_ServiceDesc is the grpc.ServiceDesc for ClusterConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.sync.v1.ClusterConfigService",
	HandlerType: (*ClusterConfigServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchClusterConfig",
			Handler:       _ClusterConfigService_WatchClusterConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandbox/sync/v1/sync.proto",
}

const (
	FederationService_ReportFederation_FullMethodName = "/sandbox.sync.v1.FederationService/ReportFederation"
	FederationService_WatchFederation_FullMethodName  = "/sandbox.sync.v1.FederationService/WatchFederation"
)

// FederationServiceClient is the client API for FederationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederationServiceClient interface {
	// ReportFederation is a Worker→Hub client stream: the Worker pushes its
	// local per-Env capacity (5 s diff / 30 s full resync). The Hub merges each
	// batch into its soft-state store and fans it out to every other Worker.
	ReportFederation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReportFederationRequest, ReportFederationResponse], error)
	// WatchFederation is a Hub→Worker server stream: the Worker receives a full
	// snapshot on connect and then every subsequent batch of foreign capacity.
	WatchFederation(ctx context.Context, in *WatchFederationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FederationBroadcast], error)
}

type federationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationServiceClient(cc grpc.ClientConnInterface) FederationServiceClient {
	return &federationServiceClient{cc}
}

func (c *federationServiceClient) ReportFederation(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ReportFederationRequest, ReportFederationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FederationService_ServiceDesc.Streams[0], FederationService_ReportFederation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReportFederationRequest, ReportFederationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_ReportFederationClient = grpc.ClientStreamingClient[ReportFederationRequest, ReportFederationResponse]

func (c *federationServiceClient) WatchFederation(ctx context.Context, in *WatchFederationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FederationBroadcast], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FederationService_ServiceDesc.Streams[1], FederationService_WatchFederation_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchFederationRequest, FederationBroadcast]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_WatchFederationClient = grpc.ServerStreamingClient[FederationBroadcast]

// FederationServiceServer is the server API for FederationService service.
// All implementations must embed UnimplementedFederationServiceServer
// for forward compatibility.
type FederationServiceServer interface {
	// ReportFederation is a Worker→Hub client stream: the Worker pushes its
	// local per-Env capacity (5 s diff / 30 s full resync). The Hub merges each
	// batch into its soft-state store and fans it out to every other Worker.
	ReportFederation(grpc.ClientStreamingServer[ReportFederationRequest, ReportFederationResponse]) error
	// WatchFederation is a Hub→Worker server stream: the Worker receives a full
	// snapshot on connect and then every subsequent batch of foreign capacity.
	WatchFederation(*WatchFederationRequest, grpc.ServerStreamingServer[FederationBroadcast]) error
	mustEmbedUnimplementedFederationServiceServer()
}

// UnimplementedFederationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationServiceServer struct{}

func (UnimplementedFederationServiceServer) ReportFederation(grpc.ClientStreamingServer[ReportFederationRequest, ReportFederationResponse]) error {
	return status.Error(codes.Unimplemented, "method ReportFederation not implemented")
}
func (UnimplementedFederationServiceServer) WatchFederation(*WatchFederationRequest, grpc.ServerStreamingServer[FederationBroadcast]) error {
	return status.Error(codes.Unimplemented, "method WatchFederation not implemented")
}
func (UnimplementedFederationServiceServer) mustEmbedUnimplementedFederationServiceServer() {}
func (UnimplementedFederationServiceServer) testEmbeddedByValue()                           {}

// UnsafeFederationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationServiceServer will
// result in compilation errors.
type UnsafeFederationServiceServer interface {
	mustEmbedUnimplementedFederationServiceServer()
}

func RegisterFederationServiceServer(s grpc.ServiceRegistrar, srv FederationServiceServer) {
	// If the following call panics, it indicates UnimplementedFederationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederationService_ServiceDesc, srv)
}

func _FederationService_ReportFederation_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FederationServiceServer).ReportFederation(&grpc.GenericServerStream[ReportFederationRequest, ReportFederationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_ReportFederationServer = grpc.ClientStreamingServer[ReportFederationRequest, ReportFederationResponse]

func _FederationService_WatchFederation_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchFederationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FederationServiceServer).WatchFederation(m, &grpc.GenericServerStream[WatchFederationRequest, FederationBroadcast]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationService_WatchFederationServer = grpc.ServerStreamingServer[FederationBroadcast]

// FederationService_ServiceDesc is the grpc.ServiceDesc for FederationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.sync.v1.FederationService",
	HandlerType: (*FederationServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportFederation",
			Handler:       _FederationService_ReportFederation_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchFederation",
			Handler:       _FederationService_WatchFederation_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sandbox/sync/v1/sync.proto",
}
