// Copyright 2026 ScitiX
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: sandbox/sync/v1/sync.proto

package syncv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// APIKeyMetadata mirrors apikey.KeyMetadata. It is the payload of WatchKeys
// upsert events and the snapshot item type.
type APIKeyMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full SHA-256 hex hash of the raw token. Used by the Worker to write a
	// matching local Secret via CreateFromHash without ever exposing the token.
	TokenHash string `protobuf:"bytes,1,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	// Short prefix derived from token_hash (currently the first 16 hex chars).
	// The Worker-side Secret name is "agentbox-apikey-{hash_prefix}".
	HashPrefix string `protobuf:"bytes,2,opt,name=hash_prefix,json=hashPrefix,proto3" json:"hash_prefix,omitempty"`
	// K8s Secret name on the Worker side — typically "agentbox-apikey-{hash_prefix}".
	// Carried explicitly so DeleteKey events can target the secret directly.
	SecretName  string                 `protobuf:"bytes,3,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Namespace   string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	User        string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Team        string                 `protobuf:"bytes,6,opt,name=team,proto3" json:"team,omitempty"`
	Role        string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	QuotaUrl    string                 `protobuf:"bytes,8,opt,name=quota_url,json=quotaUrl,proto3" json:"quota_url,omitempty"`
	Description string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	IssuedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// Zero value (unset) means the key never expires.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Plaintext token kept on the Hub side for promote / import scenarios where
	// a Worker may need to reconstruct the recoverable value. Empty for legacy
	// keys created before plaintext storage was introduced.
	RawToken      string `protobuf:"bytes,12,opt,name=raw_token,json=rawToken,proto3" json:"raw_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyMetadata) Reset() {
	*x = APIKeyMetadata{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyMetadata) ProtoMessage() {}

func (x *APIKeyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyMetadata.ProtoReflect.Descriptor instead.
func (*APIKeyMetadata) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *APIKeyMetadata) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *APIKeyMetadata) GetHashPrefix() string {
	if x != nil {
		return x.HashPrefix
	}
	return ""
}

func (x *APIKeyMetadata) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *APIKeyMetadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *APIKeyMetadata) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *APIKeyMetadata) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *APIKeyMetadata) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *APIKeyMetadata) GetQuotaUrl() string {
	if x != nil {
		return x.QuotaUrl
	}
	return ""
}

func (x *APIKeyMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *APIKeyMetadata) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *APIKeyMetadata) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *APIKeyMetadata) GetRawToken() string {
	if x != nil {
		return x.RawToken
	}
	return ""
}

type CreateKeyRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Namespace   string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	User        string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Team        string                 `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	Role        string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	QuotaUrl    string                 `protobuf:"bytes,6,opt,name=quota_url,json=quotaUrl,proto3" json:"quota_url,omitempty"`
	ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Import/promote mode. When both token_hash and hash_prefix are set the Hub
	// calls CreateFromHash (idempotent) instead of generating a new token.
	TokenHash  string                 `protobuf:"bytes,8,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	HashPrefix string                 `protobuf:"bytes,9,opt,name=hash_prefix,json=hashPrefix,proto3" json:"hash_prefix,omitempty"`
	IssuedAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// Plaintext token to store alongside the hash in import/promote mode.
	RawToken      string `protobuf:"bytes,11,opt,name=raw_token,json=rawToken,proto3" json:"raw_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyRequest) Reset() {
	*x = CreateKeyRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyRequest) ProtoMessage() {}

func (x *CreateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKeyRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateKeyRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CreateKeyRequest) GetTeam() string {
	if x != nil {
		return x.Team
	}
	return ""
}

func (x *CreateKeyRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateKeyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateKeyRequest) GetQuotaUrl() string {
	if x != nil {
		return x.QuotaUrl
	}
	return ""
}

func (x *CreateKeyRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateKeyRequest) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *CreateKeyRequest) GetHashPrefix() string {
	if x != nil {
		return x.HashPrefix
	}
	return ""
}

func (x *CreateKeyRequest) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *CreateKeyRequest) GetRawToken() string {
	if x != nil {
		return x.RawToken
	}
	return ""
}

type CreateKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw token (agbx_...) returned only when generated by the Hub. Empty for
	// import/promote mode (caller already has it).
	RawToken string `protobuf:"bytes,1,opt,name=raw_token,json=rawToken,proto3" json:"raw_token,omitempty"`
	// Fully qualified K8s Secret name on the Hub: "agentbox-apikey-{hash_prefix}".
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	HashPrefix    string                 `protobuf:"bytes,3,opt,name=hash_prefix,json=hashPrefix,proto3" json:"hash_prefix,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	TokenHash     string                 `protobuf:"bytes,5,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyResponse) Reset() {
	*x = CreateKeyResponse{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyResponse) ProtoMessage() {}

func (x *CreateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKeyResponse) GetRawToken() string {
	if x != nil {
		return x.RawToken
	}
	return ""
}

func (x *CreateKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *CreateKeyResponse) GetHashPrefix() string {
	if x != nil {
		return x.HashPrefix
	}
	return ""
}

func (x *CreateKeyResponse) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *CreateKeyResponse) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

type DeleteKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either the secret name ("agentbox-apikey-...") or the bare hash prefix.
	KeyId         string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{4}
}

type KeyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*KeyEvent_Snapshot
	//	*KeyEvent_Upsert
	//	*KeyEvent_Delete
	Kind          isKeyEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEvent) Reset() {
	*x = KeyEvent{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEvent) ProtoMessage() {}

func (x *KeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEvent.ProtoReflect.Descriptor instead.
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *KeyEvent) GetKind() isKeyEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *KeyEvent) GetSnapshot() *KeySnapshot {
	if x != nil {
		if x, ok := x.Kind.(*KeyEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *KeyEvent) GetUpsert() *APIKeyMetadata {
	if x != nil {
		if x, ok := x.Kind.(*KeyEvent_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

func (x *KeyEvent) GetDelete() *KeyDelete {
	if x != nil {
		if x, ok := x.Kind.(*KeyEvent_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isKeyEvent_Kind interface {
	isKeyEvent_Kind()
}

type KeyEvent_Snapshot struct {
	Snapshot *KeySnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type KeyEvent_Upsert struct {
	Upsert *APIKeyMetadata `protobuf:"bytes,2,opt,name=upsert,proto3,oneof"`
}

type KeyEvent_Delete struct {
	Delete *KeyDelete `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

func (*KeyEvent_Snapshot) isKeyEvent_Kind() {}

func (*KeyEvent_Upsert) isKeyEvent_Kind() {}

func (*KeyEvent_Delete) isKeyEvent_Kind() {}

type KeySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*APIKeyMetadata      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySnapshot) Reset() {
	*x = KeySnapshot{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySnapshot) ProtoMessage() {}

func (x *KeySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySnapshot.ProtoReflect.Descriptor instead.
func (*KeySnapshot) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *KeySnapshot) GetItems() []*APIKeyMetadata {
	if x != nil {
		return x.Items
	}
	return nil
}

type KeyDelete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Secret name to delete locally; matches APIKeyMetadata.secret_name.
	SecretName    string `protobuf:"bytes,1,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyDelete) Reset() {
	*x = KeyDelete{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyDelete) ProtoMessage() {}

func (x *KeyDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyDelete.ProtoReflect.Descriptor instead.
func (*KeyDelete) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *KeyDelete) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

type WatchKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchKeysRequest) Reset() {
	*x = WatchKeysRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchKeysRequest) ProtoMessage() {}

func (x *WatchKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchKeysRequest.ProtoReflect.Descriptor instead.
func (*WatchKeysRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{8}
}

type CreateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateJson  []byte                 `protobuf:"bytes,1,opt,name=template_json,json=templateJson,proto3" json:"template_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateRequest) Reset() {
	*x = CreateTemplateRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateRequest) ProtoMessage() {}

func (x *CreateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{9}
}

func (x *CreateTemplateRequest) GetTemplateJson() []byte {
	if x != nil {
		return x.TemplateJson
	}
	return nil
}

type CreateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTemplateResponse) Reset() {
	*x = CreateTemplateResponse{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTemplateResponse) ProtoMessage() {}

func (x *CreateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTemplateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateJson  []byte                 `protobuf:"bytes,1,opt,name=template_json,json=templateJson,proto3" json:"template_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateRequest) Reset() {
	*x = UpdateTemplateRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateRequest) ProtoMessage() {}

func (x *UpdateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTemplateRequest) GetTemplateJson() []byte {
	if x != nil {
		return x.TemplateJson
	}
	return nil
}

type UpdateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTemplateResponse) Reset() {
	*x = UpdateTemplateResponse{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTemplateResponse) ProtoMessage() {}

func (x *UpdateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTemplateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteTemplateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TemplateUpsert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full JSON-encoded *v1alpha1.SandboxTemplate, including ObjectMeta + Spec.
	TemplateJson  []byte `protobuf:"bytes,1,opt,name=template_json,json=templateJson,proto3" json:"template_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateUpsert) Reset() {
	*x = TemplateUpsert{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateUpsert) ProtoMessage() {}

func (x *TemplateUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateUpsert.ProtoReflect.Descriptor instead.
func (*TemplateUpsert) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{15}
}

func (x *TemplateUpsert) GetTemplateJson() []byte {
	if x != nil {
		return x.TemplateJson
	}
	return nil
}

type TemplateDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateDelete) Reset() {
	*x = TemplateDelete{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateDelete) ProtoMessage() {}

func (x *TemplateDelete) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateDelete.ProtoReflect.Descriptor instead.
func (*TemplateDelete) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{16}
}

func (x *TemplateDelete) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TemplateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateJsons [][]byte               `protobuf:"bytes,1,rep,name=template_jsons,json=templateJsons,proto3" json:"template_jsons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateSnapshot) Reset() {
	*x = TemplateSnapshot{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateSnapshot) ProtoMessage() {}

func (x *TemplateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateSnapshot.ProtoReflect.Descriptor instead.
func (*TemplateSnapshot) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{17}
}

func (x *TemplateSnapshot) GetTemplateJsons() [][]byte {
	if x != nil {
		return x.TemplateJsons
	}
	return nil
}

type TemplateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*TemplateEvent_Snapshot
	//	*TemplateEvent_Upsert
	//	*TemplateEvent_Delete
	Kind          isTemplateEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateEvent) Reset() {
	*x = TemplateEvent{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateEvent) ProtoMessage() {}

func (x *TemplateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateEvent.ProtoReflect.Descriptor instead.
func (*TemplateEvent) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{18}
}

func (x *TemplateEvent) GetKind() isTemplateEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *TemplateEvent) GetSnapshot() *TemplateSnapshot {
	if x != nil {
		if x, ok := x.Kind.(*TemplateEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *TemplateEvent) GetUpsert() *TemplateUpsert {
	if x != nil {
		if x, ok := x.Kind.(*TemplateEvent_Upsert); ok {
			return x.Upsert
		}
	}
	return nil
}

func (x *TemplateEvent) GetDelete() *TemplateDelete {
	if x != nil {
		if x, ok := x.Kind.(*TemplateEvent_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isTemplateEvent_Kind interface {
	isTemplateEvent_Kind()
}

type TemplateEvent_Snapshot struct {
	Snapshot *TemplateSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type TemplateEvent_Upsert struct {
	Upsert *TemplateUpsert `protobuf:"bytes,2,opt,name=upsert,proto3,oneof"`
}

type TemplateEvent_Delete struct {
	Delete *TemplateDelete `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

func (*TemplateEvent_Snapshot) isTemplateEvent_Kind() {}

func (*TemplateEvent_Upsert) isTemplateEvent_Kind() {}

func (*TemplateEvent_Delete) isTemplateEvent_Kind() {}

type WatchTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTemplatesRequest) Reset() {
	*x = WatchTemplatesRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTemplatesRequest) ProtoMessage() {}

func (x *WatchTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTemplatesRequest.ProtoReflect.Descriptor instead.
func (*WatchTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{19}
}

type HostAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostnames     []string               `protobuf:"bytes,2,rep,name=hostnames,proto3" json:"hostnames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostAlias) Reset() {
	*x = HostAlias{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostAlias) ProtoMessage() {}

func (x *HostAlias) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostAlias.ProtoReflect.Descriptor instead.
func (*HostAlias) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{20}
}

func (x *HostAlias) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HostAlias) GetHostnames() []string {
	if x != nil {
		return x.Hostnames
	}
	return nil
}

type RegistryEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Host  string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Pairing label across clusters; empty strings only match other empty strings.
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryEntry) Reset() {
	*x = RegistryEntry{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryEntry) ProtoMessage() {}

func (x *RegistryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryEntry.ProtoReflect.Descriptor instead.
func (*RegistryEntry) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{21}
}

func (x *RegistryEntry) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegistryEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GatewayConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NativeUrl     string                 `protobuf:"bytes,1,opt,name=native_url,json=nativeUrl,proto3" json:"native_url,omitempty"`
	E2BUrl        string                 `protobuf:"bytes,2,opt,name=e2b_url,json=e2bUrl,proto3" json:"e2b_url,omitempty"`
	DataUrl       string                 `protobuf:"bytes,3,opt,name=data_url,json=dataUrl,proto3" json:"data_url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NativeHeaders map[string]string      `protobuf:"bytes,5,rep,name=native_headers,json=nativeHeaders,proto3" json:"native_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	E2BHeaders    map[string]string      `protobuf:"bytes,6,rep,name=e2b_headers,json=e2bHeaders,proto3" json:"e2b_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DataHeaders   map[string]string      `protobuf:"bytes,7,rep,name=data_headers,json=dataHeaders,proto3" json:"data_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayConfig) Reset() {
	*x = GatewayConfig{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConfig) ProtoMessage() {}

func (x *GatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConfig.ProtoReflect.Descriptor instead.
func (*GatewayConfig) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{22}
}

func (x *GatewayConfig) GetNativeUrl() string {
	if x != nil {
		return x.NativeUrl
	}
	return ""
}

func (x *GatewayConfig) GetE2BUrl() string {
	if x != nil {
		return x.E2BUrl
	}
	return ""
}

func (x *GatewayConfig) GetDataUrl() string {
	if x != nil {
		return x.DataUrl
	}
	return ""
}

func (x *GatewayConfig) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *GatewayConfig) GetNativeHeaders() map[string]string {
	if x != nil {
		return x.NativeHeaders
	}
	return nil
}

func (x *GatewayConfig) GetE2BHeaders() map[string]string {
	if x != nil {
		return x.E2BHeaders
	}
	return nil
}

func (x *GatewayConfig) GetDataHeaders() map[string]string {
	if x != nil {
		return x.DataHeaders
	}
	return nil
}

type ClusterEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url   string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Full PromQL label matcher expression that uniquely identifies this
	// cluster's metrics, e.g. `cluster="cluster1",region="region1"`.
	Selector      string            `protobuf:"bytes,4,opt,name=selector,proto3" json:"selector,omitempty"`
	Headers       map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Visible       string            `protobuf:"bytes,6,opt,name=visible,proto3" json:"visible,omitempty"`
	Gateway       *GatewayConfig    `protobuf:"bytes,7,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Registries    []*RegistryEntry  `protobuf:"bytes,8,rep,name=registries,proto3" json:"registries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterEntry) Reset() {
	*x = ClusterEntry{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterEntry) ProtoMessage() {}

func (x *ClusterEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterEntry.ProtoReflect.Descriptor instead.
func (*ClusterEntry) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{23}
}

func (x *ClusterEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterEntry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ClusterEntry) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *ClusterEntry) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ClusterEntry) GetVisible() string {
	if x != nil {
		return x.Visible
	}
	return ""
}

func (x *ClusterEntry) GetGateway() *GatewayConfig {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *ClusterEntry) GetRegistries() []*RegistryEntry {
	if x != nil {
		return x.Registries
	}
	return nil
}

type ClusterConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clusters      []*ClusterEntry        `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	HostAliases   []*HostAlias           `protobuf:"bytes,2,rep,name=host_aliases,json=hostAliases,proto3" json:"host_aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterConfig) Reset() {
	*x = ClusterConfig{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfig) ProtoMessage() {}

func (x *ClusterConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfig.ProtoReflect.Descriptor instead.
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{24}
}

func (x *ClusterConfig) GetClusters() []*ClusterEntry {
	if x != nil {
		return x.Clusters
	}
	return nil
}

func (x *ClusterConfig) GetHostAliases() []*HostAlias {
	if x != nil {
		return x.HostAliases
	}
	return nil
}

type ClusterConfigEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full snapshot is republished on every change. The Worker MUST treat
	// an empty snapshot (no clusters and no host aliases) as a no-op so a
	// transient empty push cannot erase an already-populated ConfigMap.
	Snapshot      *ClusterConfig `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterConfigEvent) Reset() {
	*x = ClusterConfigEvent{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConfigEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfigEvent) ProtoMessage() {}

func (x *ClusterConfigEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfigEvent.ProtoReflect.Descriptor instead.
func (*ClusterConfigEvent) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{25}
}

func (x *ClusterConfigEvent) GetSnapshot() *ClusterConfig {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type WatchClusterConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchClusterConfigRequest) Reset() {
	*x = WatchClusterConfigRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchClusterConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchClusterConfigRequest) ProtoMessage() {}

func (x *WatchClusterConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchClusterConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchClusterConfigRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{26}
}

// EnvCapacity is one cluster's runtime capacity for a single member pool of a
// same-named SandboxEnv. member_pool identifies the concrete SandboxPool in
// that cluster so the origin cluster can pin cross-cluster placement to an
// exact pool (forwarding "<cluster_id>::<member_pool>"); scaling_group lets the
// origin honour a requested group.
type EnvCapacity struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ClusterId    string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespace    string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	EnvName      string                 `protobuf:"bytes,3,opt,name=env_name,json=envName,proto3" json:"env_name,omitempty"`
	ScalingGroup string                 `protobuf:"bytes,4,opt,name=scaling_group,json=scalingGroup,proto3" json:"scaling_group,omitempty"`
	Idle         int32                  `protobuf:"varint,5,opt,name=idle,proto3" json:"idle,omitempty"`
	Running      int32                  `protobuf:"varint,6,opt,name=running,proto3" json:"running,omitempty"`
	Pending      int32                  `protobuf:"varint,7,opt,name=pending,proto3" json:"pending,omitempty"`
	Desired      int32                  `protobuf:"varint,8,opt,name=desired,proto3" json:"desired,omitempty"`
	// member_pool is the SandboxPool name of this member within its cluster.
	MemberPool string `protobuf:"bytes,12,opt,name=member_pool,json=memberPool,proto3" json:"member_pool,omitempty"`
	// autoscaling_enabled reports whether this member's scaling group has the
	// autoscaler on in its owning cluster (per-member, per-cluster). Gates
	// whether capacity below is meaningful.
	AutoscalingEnabled bool `protobuf:"varint,13,opt,name=autoscaling_enabled,json=autoscalingEnabled,proto3" json:"autoscaling_enabled,omitempty"`
	// capacity is the member's remaining scale-up headroom on its owning
	// cluster, meaningful only when autoscaling_enabled: -1 = unbounded (no
	// finite ceiling), 0 = at ceiling (cannot grow now), >0 = room left.
	Capacity int32 `protobuf:"varint,9,opt,name=capacity,proto3" json:"capacity,omitempty"`
	// saturated_for is the remaining saturation window in seconds (0 = not
	// saturated). Relative to avoid cross-cluster clock skew.
	SaturatedFor int32 `protobuf:"varint,10,opt,name=saturated_for,json=saturatedFor,proto3" json:"saturated_for,omitempty"`
	// observed_for_ms is the age of this sample in milliseconds at send time.
	ObservedForMs int64 `protobuf:"varint,11,opt,name=observed_for_ms,json=observedForMs,proto3" json:"observed_for_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvCapacity) Reset() {
	*x = EnvCapacity{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvCapacity) ProtoMessage() {}

func (x *EnvCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvCapacity.ProtoReflect.Descriptor instead.
func (*EnvCapacity) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{27}
}

func (x *EnvCapacity) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *EnvCapacity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EnvCapacity) GetEnvName() string {
	if x != nil {
		return x.EnvName
	}
	return ""
}

func (x *EnvCapacity) GetScalingGroup() string {
	if x != nil {
		return x.ScalingGroup
	}
	return ""
}

func (x *EnvCapacity) GetIdle() int32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *EnvCapacity) GetRunning() int32 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *EnvCapacity) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *EnvCapacity) GetDesired() int32 {
	if x != nil {
		return x.Desired
	}
	return 0
}

func (x *EnvCapacity) GetMemberPool() string {
	if x != nil {
		return x.MemberPool
	}
	return ""
}

func (x *EnvCapacity) GetAutoscalingEnabled() bool {
	if x != nil {
		return x.AutoscalingEnabled
	}
	return false
}

func (x *EnvCapacity) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *EnvCapacity) GetSaturatedFor() int32 {
	if x != nil {
		return x.SaturatedFor
	}
	return 0
}

func (x *EnvCapacity) GetObservedForMs() int64 {
	if x != nil {
		return x.ObservedForMs
	}
	return 0
}

type ReportFederationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EnvCapacity         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFederationRequest) Reset() {
	*x = ReportFederationRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFederationRequest) ProtoMessage() {}

func (x *ReportFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFederationRequest.ProtoReflect.Descriptor instead.
func (*ReportFederationRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{28}
}

func (x *ReportFederationRequest) GetItems() []*EnvCapacity {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReportFederationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFederationResponse) Reset() {
	*x = ReportFederationResponse{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFederationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFederationResponse) ProtoMessage() {}

func (x *ReportFederationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFederationResponse.ProtoReflect.Descriptor instead.
func (*ReportFederationResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{29}
}

type FederationBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EnvCapacity         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederationBroadcast) Reset() {
	*x = FederationBroadcast{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationBroadcast) ProtoMessage() {}

func (x *FederationBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationBroadcast.ProtoReflect.Descriptor instead.
func (*FederationBroadcast) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{30}
}

func (x *FederationBroadcast) GetItems() []*EnvCapacity {
	if x != nil {
		return x.Items
	}
	return nil
}

type WatchFederationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchFederationRequest) Reset() {
	*x = WatchFederationRequest{}
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchFederationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchFederationRequest) ProtoMessage() {}

func (x *WatchFederationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sync_v1_sync_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchFederationRequest.ProtoReflect.Descriptor instead.
func (*WatchFederationRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sync_v1_sync_proto_rawDescGZIP(), []int{31}
}

var File_sandbox_sync_v1_sync_proto protoreflect.FileDescriptor

const file_sandbox_sync_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\x1asandbox/sync/v1/sync.proto\x12\x0fsandbox.sync.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x03\n" +
	"\x0eAPIKeyMetadata\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x01 \x01(\tR\ttokenHash\x12\x1f\n" +
	"\vhash_prefix\x18\x02 \x01(\tR\n" +
	"hashPrefix\x12\x1f\n" +
	"\vsecret_name\x18\x03 \x01(\tR\n" +
	"secretName\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x12\n" +
	"\x04team\x18\x06 \x01(\tR\x04team\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x1b\n" +
	"\tquota_url\x18\b \x01(\tR\bquotaUrl\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x127\n" +
	"\tissued_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1b\n" +
	"\traw_token\x18\f \x01(\tR\brawToken\"\xfc\x02\n" +
	"\x10CreateKeyRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04team\x18\x03 \x01(\tR\x04team\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1b\n" +
	"\tquota_url\x18\x06 \x01(\tR\bquotaUrl\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"token_hash\x18\b \x01(\tR\ttokenHash\x12\x1f\n" +
	"\vhash_prefix\x18\t \x01(\tR\n" +
	"hashPrefix\x127\n" +
	"\tissued_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12\x1b\n" +
	"\traw_token\x18\v \x01(\tR\brawToken\"\xc0\x01\n" +
	"\x11CreateKeyResponse\x12\x1b\n" +
	"\traw_token\x18\x01 \x01(\tR\brawToken\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1f\n" +
	"\vhash_prefix\x18\x03 \x01(\tR\n" +
	"hashPrefix\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x05 \x01(\tR\ttokenHash\")\n" +
	"\x10DeleteKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\"\x13\n" +
	"\x11DeleteKeyResponse\"\xbf\x01\n" +
	"\bKeyEvent\x12:\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1c.sandbox.sync.v1.KeySnapshotH\x00R\bsnapshot\x129\n" +
	"\x06upsert\x18\x02 \x01(\v2\x1f.sandbox.sync.v1.APIKeyMetadataH\x00R\x06upsert\x124\n" +
	"\x06delete\x18\x03 \x01(\v2\x1a.sandbox.sync.v1.KeyDeleteH\x00R\x06deleteB\x06\n" +
	"\x04kind\"D\n" +
	"\vKeySnapshot\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.sandbox.sync.v1.APIKeyMetadataR\x05items\",\n" +
	"\tKeyDelete\x12\x1f\n" +
	"\vsecret_name\x18\x01 \x01(\tR\n" +
	"secretName\"\x12\n" +
	"\x10WatchKeysRequest\"<\n" +
	"\x15CreateTemplateRequest\x12#\n" +
	"\rtemplate_json\x18\x01 \x01(\fR\ftemplateJson\",\n" +
	"\x16CreateTemplateResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"<\n" +
	"\x15UpdateTemplateRequest\x12#\n" +
	"\rtemplate_json\x18\x01 \x01(\fR\ftemplateJson\",\n" +
	"\x16UpdateTemplateResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"+\n" +
	"\x15DeleteTemplateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\",\n" +
	"\x16DeleteTemplateResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"5\n" +
	"\x0eTemplateUpsert\x12#\n" +
	"\rtemplate_json\x18\x01 \x01(\fR\ftemplateJson\"$\n" +
	"\x0eTemplateDelete\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\x10TemplateSnapshot\x12%\n" +
	"\x0etemplate_jsons\x18\x01 \x03(\fR\rtemplateJsons\"\xce\x01\n" +
	"\rTemplateEvent\x12?\n" +
	"\bsnapshot\x18\x01 \x01(\v2!.sandbox.sync.v1.TemplateSnapshotH\x00R\bsnapshot\x129\n" +
	"\x06upsert\x18\x02 \x01(\v2\x1f.sandbox.sync.v1.TemplateUpsertH\x00R\x06upsert\x129\n" +
	"\x06delete\x18\x03 \x01(\v2\x1f.sandbox.sync.v1.TemplateDeleteH\x00R\x06deleteB\x06\n" +
	"\x04kind\"\x17\n" +
	"\x15WatchTemplatesRequest\"9\n" +
	"\tHostAlias\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1c\n" +
	"\thostnames\x18\x02 \x03(\tR\thostnames\"7\n" +
	"\rRegistryEntry\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\xa5\x05\n" +
	"\rGatewayConfig\x12\x1d\n" +
	"\n" +
	"native_url\x18\x01 \x01(\tR\tnativeUrl\x12\x17\n" +
	"\ae2b_url\x18\x02 \x01(\tR\x06e2bUrl\x12\x19\n" +
	"\bdata_url\x18\x03 \x01(\tR\adataUrl\x12E\n" +
	"\aheaders\x18\x04 \x03(\v2+.sandbox.sync.v1.GatewayConfig.HeadersEntryR\aheaders\x12X\n" +
	"\x0enative_headers\x18\x05 \x03(\v21.sandbox.sync.v1.GatewayConfig.NativeHeadersEntryR\rnativeHeaders\x12O\n" +
	"\ve2b_headers\x18\x06 \x03(\v2..sandbox.sync.v1.GatewayConfig.E2bHeadersEntryR\n" +
	"e2bHeaders\x12R\n" +
	"\fdata_headers\x18\a \x03(\v2/.sandbox.sync.v1.GatewayConfig.DataHeadersEntryR\vdataHeaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12NativeHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fE2bHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10DataHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf6\x02\n" +
	"\fClusterEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bselector\x18\x04 \x01(\tR\bselector\x12D\n" +
	"\aheaders\x18\x05 \x03(\v2*.sandbox.sync.v1.ClusterEntry.HeadersEntryR\aheaders\x12\x18\n" +
	"\avisible\x18\x06 \x01(\tR\avisible\x128\n" +
	"\agateway\x18\a \x01(\v2\x1e.sandbox.sync.v1.GatewayConfigR\agateway\x12>\n" +
	"\n" +
	"registries\x18\b \x03(\v2\x1e.sandbox.sync.v1.RegistryEntryR\n" +
	"registries\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x89\x01\n" +
	"\rClusterConfig\x129\n" +
	"\bclusters\x18\x01 \x03(\v2\x1d.sandbox.sync.v1.ClusterEntryR\bclusters\x12=\n" +
	"\fhost_aliases\x18\x02 \x03(\v2\x1a.sandbox.sync.v1.HostAliasR\vhostAliases\"P\n" +
	"\x12ClusterConfigEvent\x12:\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1e.sandbox.sync.v1.ClusterConfigR\bsnapshot\"\x1b\n" +
	"\x19WatchClusterConfigRequest\"\xa7\x03\n" +
	"\vEnvCapacity\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\benv_name\x18\x03 \x01(\tR\aenvName\x12#\n" +
	"\rscaling_group\x18\x04 \x01(\tR\fscalingGroup\x12\x12\n" +
	"\x04idle\x18\x05 \x01(\x05R\x04idle\x12\x18\n" +
	"\arunning\x18\x06 \x01(\x05R\arunning\x12\x18\n" +
	"\apending\x18\a \x01(\x05R\apending\x12\x18\n" +
	"\adesired\x18\b \x01(\x05R\adesired\x12\x1f\n" +
	"\vmember_pool\x18\f \x01(\tR\n" +
	"memberPool\x12/\n" +
	"\x13autoscaling_enabled\x18\r \x01(\bR\x12autoscalingEnabled\x12\x1a\n" +
	"\bcapacity\x18\t \x01(\x05R\bcapacity\x12#\n" +
	"\rsaturated_for\x18\n" +
	" \x01(\x05R\fsaturatedFor\x12&\n" +
	"\x0fobserved_for_ms\x18\v \x01(\x03R\robservedForMs\"M\n" +
	"\x17ReportFederationRequest\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.sandbox.sync.v1.EnvCapacityR\x05items\"\x1a\n" +
	"\x18ReportFederationResponse\"I\n" +
	"\x13FederationBroadcast\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.sandbox.sync.v1.EnvCapacityR\x05items\"\x18\n" +
	"\x16WatchFederationRequest2\x84\x02\n" +
	"\rAPIKeyService\x12R\n" +
	"\tCreateKey\x12!.sandbox.sync.v1.CreateKeyRequest\x1a\".sandbox.sync.v1.CreateKeyResponse\x12R\n" +
	"\tDeleteKey\x12!.sandbox.sync.v1.DeleteKeyRequest\x1a\".sandbox.sync.v1.DeleteKeyResponse\x12K\n" +
	"\tWatchKeys\x12!.sandbox.sync.v1.WatchKeysRequest\x1a\x19.sandbox.sync.v1.KeyEvent0\x012\x96\x03\n" +
	"\x0fTemplateService\x12a\n" +
	"\x0eCreateTemplate\x12&.sandbox.sync.v1.CreateTemplateRequest\x1a'.sandbox.sync.v1.CreateTemplateResponse\x12a\n" +
	"\x0eUpdateTemplate\x12&.sandbox.sync.v1.UpdateTemplateRequest\x1a'.sandbox.sync.v1.UpdateTemplateResponse\x12a\n" +
	"\x0eDeleteTemplate\x12&.sandbox.sync.v1.DeleteTemplateRequest\x1a'.sandbox.sync.v1.DeleteTemplateResponse\x12Z\n" +
	"\x0eWatchTemplates\x12&.sandbox.sync.v1.WatchTemplatesRequest\x1a\x1e.sandbox.sync.v1.TemplateEvent0\x012\x7f\n" +
	"\x14ClusterConfigService\x12g\n" +
	"\x12WatchClusterConfig\x12*.sandbox.sync.v1.WatchClusterConfigRequest\x1a#.sandbox.sync.v1.ClusterConfigEvent0\x012\xe2\x01\n" +
	"\x11FederationService\x12i\n" +
	"\x10ReportFederation\x12(.sandbox.sync.v1.ReportFederationRequest\x1a).sandbox.sync.v1.ReportFederationResponse(\x01\x12b\n" +
	"\x0fWatchFederation\x12'.sandbox.sync.v1.WatchFederationRequest\x1a$.sandbox.sync.v1.FederationBroadcast0\x01BBZ@github.com/scitix/agent-sandbox/pkg/proto/sandbox/sync/v1;syncv1b\x06proto3"

var (
	file_sandbox_sync_v1_sync_proto_rawDescOnce sync.Once
	file_sandbox_sync_v1_sync_proto_rawDescData []byte
)

func file_sandbox_sync_v1_sync_proto_rawDescGZIP() []byte {
	file_sandbox_sync_v1_sync_proto_rawDescOnce.Do(func() {
		file_sandbox_sync_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_sync_v1_sync_proto_rawDesc), len(file_sandbox_sync_v1_sync_proto_rawDesc)))
	})
	return file_sandbox_sync_v1_sync_proto_rawDescData
}

var file_sandbox_sync_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_sandbox_sync_v1_sync_proto_goTypes = []any{
	(*APIKeyMetadata)(nil),            // 0: sandbox.sync.v1.APIKeyMetadata
	(*CreateKeyRequest)(nil),          // 1: sandbox.sync.v1.CreateKeyRequest
	(*CreateKeyResponse)(nil),         // 2: sandbox.sync.v1.CreateKeyResponse
	(*DeleteKeyRequest)(nil),          // 3: sandbox.sync.v1.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),         // 4: sandbox.sync.v1.DeleteKeyResponse
	(*KeyEvent)(nil),                  // 5: sandbox.sync.v1.KeyEvent
	(*KeySnapshot)(nil),               // 6: sandbox.sync.v1.KeySnapshot
	(*KeyDelete)(nil),                 // 7: sandbox.sync.v1.KeyDelete
	(*WatchKeysRequest)(nil),          // 8: sandbox.sync.v1.WatchKeysRequest
	(*CreateTemplateRequest)(nil),     // 9: sandbox.sync.v1.CreateTemplateRequest
	(*CreateTemplateResponse)(nil),    // 10: sandbox.sync.v1.CreateTemplateResponse
	(*UpdateTemplateRequest)(nil),     // 11: sandbox.sync.v1.UpdateTemplateRequest
	(*UpdateTemplateResponse)(nil),    // 12: sandbox.sync.v1.UpdateTemplateResponse
	(*DeleteTemplateRequest)(nil),     // 13: sandbox.sync.v1.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil),    // 14: sandbox.sync.v1.DeleteTemplateResponse
	(*TemplateUpsert)(nil),            // 15: sandbox.sync.v1.TemplateUpsert
	(*TemplateDelete)(nil),            // 16: sandbox.sync.v1.TemplateDelete
	(*TemplateSnapshot)(nil),          // 17: sandbox.sync.v1.TemplateSnapshot
	(*TemplateEvent)(nil),             // 18: sandbox.sync.v1.TemplateEvent
	(*WatchTemplatesRequest)(nil),     // 19: sandbox.sync.v1.WatchTemplatesRequest
	(*HostAlias)(nil),                 // 20: sandbox.sync.v1.HostAlias
	(*RegistryEntry)(nil),             // 21: sandbox.sync.v1.RegistryEntry
	(*GatewayConfig)(nil),             // 22: sandbox.sync.v1.GatewayConfig
	(*ClusterEntry)(nil),              // 23: sandbox.sync.v1.ClusterEntry
	(*ClusterConfig)(nil),             // 24: sandbox.sync.v1.ClusterConfig
	(*ClusterConfigEvent)(nil),        // 25: sandbox.sync.v1.ClusterConfigEvent
	(*WatchClusterConfigRequest)(nil), // 26: sandbox.sync.v1.WatchClusterConfigRequest
	(*EnvCapacity)(nil),               // 27: sandbox.sync.v1.EnvCapacity
	(*ReportFederationRequest)(nil),   // 28: sandbox.sync.v1.ReportFederationRequest
	(*ReportFederationResponse)(nil),  // 29: sandbox.sync.v1.ReportFederationResponse
	(*FederationBroadcast)(nil),       // 30: sandbox.sync.v1.FederationBroadcast
	(*WatchFederationRequest)(nil),    // 31: sandbox.sync.v1.WatchFederationRequest
	nil,                               // 32: sandbox.sync.v1.GatewayConfig.HeadersEntry
	nil,                               // 33: sandbox.sync.v1.GatewayConfig.NativeHeadersEntry
	nil,                               // 34: sandbox.sync.v1.GatewayConfig.E2bHeadersEntry
	nil,                               // 35: sandbox.sync.v1.GatewayConfig.DataHeadersEntry
	nil,                               // 36: sandbox.sync.v1.ClusterEntry.HeadersEntry
	(*timestamppb.Timestamp)(nil),     // 37: google.protobuf.Timestamp
}
var file_sandbox_sync_v1_sync_proto_depIdxs = []int32{
	37, // 0: sandbox.sync.v1.APIKeyMetadata.issued_at:type_name -> google.protobuf.Timestamp
	37, // 1: sandbox.sync.v1.APIKeyMetadata.expires_at:type_name -> google.protobuf.Timestamp
	37, // 2: sandbox.sync.v1.CreateKeyRequest.expires_at:type_name -> google.protobuf.Timestamp
	37, // 3: sandbox.sync.v1.CreateKeyRequest.issued_at:type_name -> google.protobuf.Timestamp
	37, // 4: sandbox.sync.v1.CreateKeyResponse.issued_at:type_name -> google.protobuf.Timestamp
	6,  // 5: sandbox.sync.v1.KeyEvent.snapshot:type_name -> sandbox.sync.v1.KeySnapshot
	0,  // 6: sandbox.sync.v1.KeyEvent.upsert:type_name -> sandbox.sync.v1.APIKeyMetadata
	7,  // 7: sandbox.sync.v1.KeyEvent.delete:type_name -> sandbox.sync.v1.KeyDelete
	0,  // 8: sandbox.sync.v1.KeySnapshot.items:type_name -> sandbox.sync.v1.APIKeyMetadata
	17, // 9: sandbox.sync.v1.TemplateEvent.snapshot:type_name -> sandbox.sync.v1.TemplateSnapshot
	15, // 10: sandbox.sync.v1.TemplateEvent.upsert:type_name -> sandbox.sync.v1.TemplateUpsert
	16, // 11: sandbox.sync.v1.TemplateEvent.delete:type_name -> sandbox.sync.v1.TemplateDelete
	32, // 12: sandbox.sync.v1.GatewayConfig.headers:type_name -> sandbox.sync.v1.GatewayConfig.HeadersEntry
	33, // 13: sandbox.sync.v1.GatewayConfig.native_headers:type_name -> sandbox.sync.v1.GatewayConfig.NativeHeadersEntry
	34, // 14: sandbox.sync.v1.GatewayConfig.e2b_headers:type_name -> sandbox.sync.v1.GatewayConfig.E2bHeadersEntry
	35, // 15: sandbox.sync.v1.GatewayConfig.data_headers:type_name -> sandbox.sync.v1.GatewayConfig.DataHeadersEntry
	36, // 16: sandbox.sync.v1.ClusterEntry.headers:type_name -> sandbox.sync.v1.ClusterEntry.HeadersEntry
	22, // 17: sandbox.sync.v1.ClusterEntry.gateway:type_name -> sandbox.sync.v1.GatewayConfig
	21, // 18: sandbox.sync.v1.ClusterEntry.registries:type_name -> sandbox.sync.v1.RegistryEntry
	23, // 19: sandbox.sync.v1.ClusterConfig.clusters:type_name -> sandbox.sync.v1.ClusterEntry
	20, // 20: sandbox.sync.v1.ClusterConfig.host_aliases:type_name -> sandbox.sync.v1.HostAlias
	24, // 21: sandbox.sync.v1.ClusterConfigEvent.snapshot:type_name -> sandbox.sync.v1.ClusterConfig
	27, // 22: sandbox.sync.v1.ReportFederationRequest.items:type_name -> sandbox.sync.v1.EnvCapacity
	27, // 23: sandbox.sync.v1.FederationBroadcast.items:type_name -> sandbox.sync.v1.EnvCapacity
	1,  // 24: sandbox.sync.v1.APIKeyService.CreateKey:input_type -> sandbox.sync.v1.CreateKeyRequest
	3,  // 25: sandbox.sync.v1.APIKeyService.DeleteKey:input_type -> sandbox.sync.v1.DeleteKeyRequest
	8,  // 26: sandbox.sync.v1.APIKeyService.WatchKeys:input_type -> sandbox.sync.v1.WatchKeysRequest
	9,  // 27: sandbox.sync.v1.TemplateService.CreateTemplate:input_type -> sandbox.sync.v1.CreateTemplateRequest
	11, // 28: sandbox.sync.v1.TemplateService.UpdateTemplate:input_type -> sandbox.sync.v1.UpdateTemplateRequest
	13, // 29: sandbox.sync.v1.TemplateService.DeleteTemplate:input_type -> sandbox.sync.v1.DeleteTemplateRequest
	19, // 30: sandbox.sync.v1.TemplateService.WatchTemplates:input_type -> sandbox.sync.v1.WatchTemplatesRequest
	26, // 31: sandbox.sync.v1.ClusterConfigService.WatchClusterConfig:input_type -> sandbox.sync.v1.WatchClusterConfigRequest
	28, // 32: sandbox.sync.v1.FederationService.ReportFederation:input_type -> sandbox.sync.v1.ReportFederationRequest
	31, // 33: sandbox.sync.v1.FederationService.WatchFederation:input_type -> sandbox.sync.v1.WatchFederationRequest
	2,  // 34: sandbox.sync.v1.APIKeyService.CreateKey:output_type -> sandbox.sync.v1.CreateKeyResponse
	4,  // 35: sandbox.sync.v1.APIKeyService.DeleteKey:output_type -> sandbox.sync.v1.DeleteKeyResponse
	5,  // 36: sandbox.sync.v1.APIKeyService.WatchKeys:output_type -> sandbox.sync.v1.KeyEvent
	10, // 37: sandbox.sync.v1.TemplateService.CreateTemplate:output_type -> sandbox.sync.v1.CreateTemplateResponse
	12, // 38: sandbox.sync.v1.TemplateService.UpdateTemplate:output_type -> sandbox.sync.v1.UpdateTemplateResponse
	14, // 39: sandbox.sync.v1.TemplateService.DeleteTemplate:output_type -> sandbox.sync.v1.DeleteTemplateResponse
	18, // 40: sandbox.sync.v1.TemplateService.WatchTemplates:output_type -> sandbox.sync.v1.TemplateEvent
	25, // 41: sandbox.sync.v1.ClusterConfigService.WatchClusterConfig:output_type -> sandbox.sync.v1.ClusterConfigEvent
	29, // 42: sandbox.sync.v1.FederationService.ReportFederation:output_type -> sandbox.sync.v1.ReportFederationResponse
	30, // 43: sandbox.sync.v1.FederationService.WatchFederation:output_type -> sandbox.sync.v1.FederationBroadcast
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_sandbox_sync_v1_sync_proto_init() }
func file_sandbox_sync_v1_sync_proto_init() {
	if File_sandbox_sync_v1_sync_proto != nil {
		return
	}
	file_sandbox_sync_v1_sync_proto_msgTypes[5].OneofWrappers = []any{
		(*KeyEvent_Snapshot)(nil),
		(*KeyEvent_Upsert)(nil),
		(*KeyEvent_Delete)(nil),
	}
	file_sandbox_sync_v1_sync_proto_msgTypes[18].OneofWrappers = []any{
		(*TemplateEvent_Snapshot)(nil),
		(*TemplateEvent_Upsert)(nil),
		(*TemplateEvent_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_sync_v1_sync_proto_rawDesc), len(file_sandbox_sync_v1_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_sandbox_sync_v1_sync_proto_goTypes,
		DependencyIndexes: file_sandbox_sync_v1_sync_proto_depIdxs,
		MessageInfos:      file_sandbox_sync_v1_sync_proto_msgTypes,
	}.Build()
	File_sandbox_sync_v1_sync_proto = out.File
	file_sandbox_sync_v1_sync_proto_goTypes = nil
	file_sandbox_sync_v1_sync_proto_depIdxs = nil
}
