// Copyright 2026 ScitiX
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package handlers implements the E2B-compatible StrictServerInterface generated by oapi-codegen.
// Supported operations delegate to the AgentBox service layer; unsupported operations return 501.
package handlers

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"strconv"
	"strings"
	"time"

	"sigs.k8s.io/controller-runtime/pkg/client"

	"k8s.io/apimachinery/pkg/api/errors"

	agentsv1alpha1 "github.com/scitix/agent-sandbox/api/v1alpha1"
	apidomain "github.com/scitix/agent-sandbox/pkg/apiserver/domain"
	"github.com/scitix/agent-sandbox/pkg/apiserver/service"
	e2bdomain "github.com/scitix/agent-sandbox/pkg/e2bcompat/domain"
	e2bgen "github.com/scitix/agent-sandbox/pkg/e2bcompat/gen"
	"github.com/scitix/agent-sandbox/pkg/utils/cluster"
	"github.com/scitix/agent-sandbox/pkg/utils/httpctx"
	"github.com/scitix/agent-sandbox/pkg/utils/httplog"
)

// Services bundles service dependencies for E2B handlers.
type Services struct {
	Sandbox service.SandboxService
	APIKey  service.APIKeyService
	// Forwarder enables cross-cluster forwarding via E2B API.
	// localClusterID is embedded in the forwarder itself; no separate field needed.
	// When Forwarder is nil, cross-cluster requests will be rejected.
	Forwarder *service.CrossClusterForwarder
}

// Server implements e2bgen.StrictServerInterface.
// Supported: GET/POST /sandboxes, GET/DELETE /sandboxes/:id, POST /sandboxes/:id/timeout,
//
//	GET /templates, GET /templates/:id, GET/POST/DELETE /api-keys, GET /health
//
// All other methods return 501 Not Implemented.
type Server struct {
	sandbox       service.SandboxService
	apikey        service.APIKeyService
	k8sClient     client.Client
	gatewayDomain string
	forwarder     *service.CrossClusterForwarder
}

// NewServer creates a new E2B handler Server.
func NewServer(svcs Services, k8sClient client.Client, gatewayDomain string) *Server {
	return &Server{
		sandbox:       svcs.Sandbox,
		apikey:        svcs.APIKey,
		k8sClient:     k8sClient,
		gatewayDomain: gatewayDomain,
		forwarder:     svcs.Forwarder,
	}
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// authFrom extracts AuthInfo from the context.
// Works with both raw *gin.Context and wrapped contexts.
func authFrom(ctx context.Context) apidomain.AuthInfo {
	return httpctx.AuthFrom(ctx)
}

// errRespAppErr converts an AppError from the service layer to an E2B-shaped
// error body. It also emits a structured klog entry via httplog so 5xx
// responses always have a matching server-side log line.
func errRespAppErr(ctx context.Context, appErr *apidomain.AppError) e2bgen.Error {
	httplog.LogAppError(httpctx.GinFromCtx(ctx), appErr)
	return e2bgen.Error{Code: int32(appErr.Code), Message: appErr.Message}
}

// errResp is retained for places that only have a string message (no
// AppError). Callers that have a non-nil underlying cause should prefer
// errRespServer so the cause is logged.
func errResp(msg string) e2bgen.Error {
	return e2bgen.Error{Code: 500, Message: msg}
}

// errRespServer logs a server-side (5xx) error that did not go through the
// AppError abstraction and returns the E2B error body.
func errRespServer(ctx context.Context, cause error, msg string) e2bgen.Error {
	httplog.LogServerError(httpctx.GinFromCtx(ctx), cause, msg)
	return e2bgen.Error{Code: 500, Message: msg}
}

func errRespCode(code int32, msg string) e2bgen.Error {
	return e2bgen.Error{Code: code, Message: msg}
}

func notImplemented() e2bgen.Error {
	return e2bgen.Error{Code: 501, Message: "not supported in AgentBox"}
}

// jsonBody marshals v to JSON and returns it as an io.Reader.
// Used when forwarding cross-cluster requests whose body has already been
// consumed by the strict-server framework.
func jsonBody(v any) io.Reader {
	b, err := json.Marshal(v)
	if err != nil {
		return nil
	}
	return bytes.NewReader(b)
}

// isCrossCluster reports whether clusterID refers to a remote cluster.
// Delegates to the forwarder's nil-safe IsCrossCluster.
func (s *Server) isCrossCluster(clusterID string) bool {
	return s.forwarder.IsCrossCluster(clusterID)
}

// loadPool fetches a SandboxPool from K8s. Returns nil on error/missing.
func (s *Server) loadPool(ctx context.Context, namespace, poolName string) *agentsv1alpha1.SandboxPool {
	if s.k8sClient == nil || poolName == "" {
		return nil
	}
	pool := &agentsv1alpha1.SandboxPool{}
	if err := s.k8sClient.Get(ctx, client.ObjectKey{Namespace: namespace, Name: poolName}, pool); err != nil {
		return nil
	}
	return pool
}

// loadPoolMap fetches all SandboxPools in a namespace as a map keyed by name.
func (s *Server) loadPoolMap(ctx context.Context, namespace string) map[string]*agentsv1alpha1.SandboxPool {
	if s.k8sClient == nil {
		return nil
	}
	poolList := &agentsv1alpha1.SandboxPoolList{}
	if err := s.k8sClient.List(ctx, poolList, client.InNamespace(namespace)); err != nil {
		return nil
	}
	m := make(map[string]*agentsv1alpha1.SandboxPool, len(poolList.Items))
	for i := range poolList.Items {
		m[poolList.Items[i].Name] = &poolList.Items[i]
	}
	return m
}

// domainSandboxToE2BSandbox converts an AgentBox domain Sandbox to an E2B Sandbox response.
func (s *Server) domainSandboxToE2BSandbox(ctx context.Context, sb *apidomain.Sandbox, namespace string) e2bgen.Sandbox {
	pool := s.loadPool(ctx, namespace, sb.PoolName)
	return e2bdomain.ToE2BSandbox(sb, pool, s.gatewayDomain)
}

// domainSandboxToSandboxDetail converts a domain Sandbox to an E2B SandboxDetail.
func (s *Server) domainSandboxToSandboxDetail(ctx context.Context, sb *apidomain.Sandbox, namespace string) e2bgen.SandboxDetail {
	pool := s.loadPool(ctx, namespace, sb.PoolName)
	return e2bdomain.ToE2BSandboxDetail(sb, pool, s.gatewayDomain)
}

// domainSandboxToListedSandbox converts a domain Sandbox to an E2B ListedSandbox.
func domainSandboxToListedSandbox(sb *apidomain.Sandbox, pool *agentsv1alpha1.SandboxPool) e2bgen.ListedSandbox {
	return e2bdomain.ToE2BListedSandbox(sb, pool)
}

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------

func (s *Server) GetHealth(_ context.Context, _ e2bgen.GetHealthRequestObject) (e2bgen.GetHealthResponseObject, error) {
	return e2bgen.GetHealth200Response{}, nil
}

// ---------------------------------------------------------------------------
// Sandboxes
// ---------------------------------------------------------------------------

// imageOverrideMetaKey is the reserved metadata key used to override the sandbox main container image
// via the E2B-compatible API. This key is consumed internally and will NOT be forwarded to sandbox metadata.
const imageOverrideMetaKey = "agentbox.scitix.ai/image"

// startupTimeoutMetaKey is the reserved metadata key used to override the sandbox startup timeout
// via the E2B-compatible API. Value is in seconds (integer string). This key is consumed internally
// and will NOT be forwarded to sandbox metadata.
const startupTimeoutMetaKey = "agentbox.scitix.ai/startup-timeout"

func (s *Server) PostSandboxes(ctx context.Context, req e2bgen.PostSandboxesRequestObject) (e2bgen.PostSandboxesResponseObject, error) {
	if req.Body == nil || strings.TrimSpace(req.Body.TemplateID) == "" {
		return e2bgen.PostSandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(errRespCode(400, "templateID is required"))}, nil
	}

	parsed := cluster.ParsePoolRef(req.Body.TemplateID)
	if parsed.PoolName == "" {
		return e2bgen.PostSandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(errRespCode(400, "templateID is required"))}, nil
	}

	auth := authFrom(ctx)
	input := apidomain.CreateSandboxInput{
		ClusterID: parsed.ClusterID,
		PoolName:  parsed.PoolName,
		Namespace: auth.Namespace,
		Image:     parsed.ImageOverride, // Option B: image embedded via "poolName//image" syntax
	}
	if req.Body.Metadata != nil {
		input.Metadata = map[string]string(*req.Body.Metadata)
		// Image override: new key takes priority over legacy key.
		// Both keys are consumed and NOT forwarded to sandbox metadata.
		if img, ok := input.Metadata[imageOverrideMetaKey]; ok && img != "" {
			input.Image = img
			delete(input.Metadata, imageOverrideMetaKey)
		}
		// Startup timeout override via metadata (value in seconds).
		// Consumed and NOT forwarded to sandbox metadata.
		if raw, ok := input.Metadata[startupTimeoutMetaKey]; ok && raw != "" {
			if secs, err := strconv.Atoi(raw); err == nil && secs > 0 {
				input.StartupTimeout = time.Duration(secs) * time.Second
			}
			delete(input.Metadata, startupTimeoutMetaKey)
		}
	}
	if req.Body.EnvVars != nil && len(*req.Body.EnvVars) > 0 {
		input.PostStartHooks = []apidomain.PostStartHookAction{{
			HTTPPost: &apidomain.HTTPPostHookAction{
				Port: 49983,
				Path: "/init",
				Body: map[string]any{
					"envVars": map[string]string(*req.Body.EnvVars),
				},
			},
		}}
	}
	if req.Body.Timeout != nil && *req.Body.Timeout > 0 {
		input.IdleTimeout = time.Duration(*req.Body.Timeout) * time.Second
	}
	// Inject team/user from auth into labels so they are recorded on the pod
	// and metrics (agentbox_sandbox_create_total) carry the correct dimensions.
	input.Labels = make(map[string]string)
	if auth.Team != "" {
		input.Labels[agentsv1alpha1.LabelTeam] = auth.Team
	}
	if auth.User != "" {
		input.Labels[agentsv1alpha1.LabelUser] = auth.User
	}

	// Cross-cluster forwarding: if the pool references a remote cluster, forward
	// the request to that cluster's E2B API.
	if s.isCrossCluster(input.ClusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), input.ClusterID, service.URLKindE2B, jsonBody(req.Body))
		return nil, nil
	}

	result, appErr := s.sandbox.Create(ctx, input)
	if appErr != nil {
		switch appErr.Code {
		case apidomain.ErrCodeNotFound:
			return e2bgen.PostSandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(errRespCode(400, appErr.Message))}, nil
		default:
			return e2bgen.PostSandboxes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
		}
	}

	sb := s.domainSandboxToE2BSandbox(ctx, result, auth.Namespace)
	return e2bgen.PostSandboxes201JSONResponse(sb), nil
}

func (s *Server) GetSandboxes(ctx context.Context, _ e2bgen.GetSandboxesRequestObject) (e2bgen.GetSandboxesResponseObject, error) {
	auth := authFrom(ctx)
	result, appErr := s.sandbox.List(ctx, apidomain.ListSandboxesFilter{
		Namespace: auth.Namespace,
		Team:      auth.Team,
		User:      auth.User,
		Limit:     0,
	})
	if appErr != nil {
		return e2bgen.GetSandboxes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	poolMap := s.loadPoolMap(ctx, auth.Namespace)

	items := make([]e2bgen.ListedSandbox, 0, len(result.Items))
	for i := range result.Items {
		sb := &result.Items[i]
		pool := poolMap[sb.PoolName]
		items = append(items, domainSandboxToListedSandbox(sb, pool))
	}

	return e2bgen.GetSandboxes200JSONResponse(items), nil
}

func (s *Server) GetSandboxesSandboxID(ctx context.Context, req e2bgen.GetSandboxesSandboxIDRequestObject) (e2bgen.GetSandboxesSandboxIDResponseObject, error) {
	auth := authFrom(ctx)
	sandboxID := string(req.SandboxID)
	if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, nil)
		return nil, nil
	}
	result, appErr := s.sandbox.Get(ctx, auth.Namespace, sandboxID)
	if appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.GetSandboxesSandboxID404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.GetSandboxesSandboxID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	detail := s.domainSandboxToSandboxDetail(ctx, result, auth.Namespace)
	return e2bgen.GetSandboxesSandboxID200JSONResponse(detail), nil
}

func (s *Server) DeleteSandboxesSandboxID(ctx context.Context, req e2bgen.DeleteSandboxesSandboxIDRequestObject) (e2bgen.DeleteSandboxesSandboxIDResponseObject, error) {
	auth := authFrom(ctx)
	sandboxID := string(req.SandboxID)
	if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, nil)
		return nil, nil
	}
	_, appErr := s.sandbox.Delete(ctx, auth.Namespace, sandboxID)
	if appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.DeleteSandboxesSandboxID404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.DeleteSandboxesSandboxID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}
	return e2bgen.DeleteSandboxesSandboxID204Response{}, nil
}

func (s *Server) PostSandboxesSandboxIDTimeout(ctx context.Context, req e2bgen.PostSandboxesSandboxIDTimeoutRequestObject) (e2bgen.PostSandboxesSandboxIDTimeoutResponseObject, error) {
	if req.Body == nil || req.Body.Timeout <= 0 {
		return e2bgen.PostSandboxesSandboxIDTimeout401JSONResponse{N401JSONResponse: e2bgen.N401JSONResponse(errRespCode(400, "timeout must be a positive integer (seconds)"))}, nil
	}

	auth := authFrom(ctx)
	sandboxID := string(req.SandboxID)
	timeout := time.Duration(req.Body.Timeout) * time.Second
	if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, jsonBody(req.Body))
		return nil, nil
	}
	if appErr := s.sandbox.SetTimeout(ctx, auth.Namespace, sandboxID, timeout); appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.PostSandboxesSandboxIDTimeout404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.PostSandboxesSandboxIDTimeout500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}
	return e2bgen.PostSandboxesSandboxIDTimeout204Response{}, nil
}

func (s *Server) PostSandboxesSandboxIDRefreshes(ctx context.Context, req e2bgen.PostSandboxesSandboxIDRefreshesRequestObject) (e2bgen.PostSandboxesSandboxIDRefreshesResponseObject, error) {
	// Refreshes = extend idle timeout to keep the sandbox alive.
	if req.Body != nil && req.Body.Duration != nil && *req.Body.Duration > 0 {
		auth := authFrom(ctx)
		sandboxID := string(req.SandboxID)
		timeout := time.Duration(*req.Body.Duration) * time.Second
		if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
			s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, jsonBody(req.Body))
			return nil, nil
		}
		if appErr := s.sandbox.SetTimeout(ctx, auth.Namespace, sandboxID, timeout); appErr != nil {
			if appErr.Code == apidomain.ErrCodeNotFound {
				return e2bgen.PostSandboxesSandboxIDRefreshes404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
			}
			return e2bgen.PostSandboxesSandboxIDRefreshes401JSONResponse{N401JSONResponse: e2bgen.N401JSONResponse(errRespCode(500, appErr.Message))}, nil
		}
	}
	return e2bgen.PostSandboxesSandboxIDRefreshes204Response{}, nil
}

// Not supported operations — return 501

func (s *Server) PostSandboxesSandboxIDPause(_ context.Context, _ e2bgen.PostSandboxesSandboxIDPauseRequestObject) (e2bgen.PostSandboxesSandboxIDPauseResponseObject, error) {
	return e2bgen.PostSandboxesSandboxIDPause500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostSandboxesSandboxIDResume(_ context.Context, _ e2bgen.PostSandboxesSandboxIDResumeRequestObject) (e2bgen.PostSandboxesSandboxIDResumeResponseObject, error) {
	return e2bgen.PostSandboxesSandboxIDResume500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostSandboxesSandboxIDSnapshots(_ context.Context, _ e2bgen.PostSandboxesSandboxIDSnapshotsRequestObject) (e2bgen.PostSandboxesSandboxIDSnapshotsResponseObject, error) {
	return e2bgen.PostSandboxesSandboxIDSnapshots500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostSandboxesSandboxIDConnect(_ context.Context, _ e2bgen.PostSandboxesSandboxIDConnectRequestObject) (e2bgen.PostSandboxesSandboxIDConnectResponseObject, error) {
	return e2bgen.PostSandboxesSandboxIDConnect500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetSandboxesMetrics(_ context.Context, _ e2bgen.GetSandboxesMetricsRequestObject) (e2bgen.GetSandboxesMetricsResponseObject, error) {
	return e2bgen.GetSandboxesMetrics500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetSandboxesSandboxIDLogs(_ context.Context, _ e2bgen.GetSandboxesSandboxIDLogsRequestObject) (e2bgen.GetSandboxesSandboxIDLogsResponseObject, error) {
	return e2bgen.GetSandboxesSandboxIDLogs500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetSandboxesSandboxIDMetrics(_ context.Context, _ e2bgen.GetSandboxesSandboxIDMetricsRequestObject) (e2bgen.GetSandboxesSandboxIDMetricsResponseObject, error) {
	return e2bgen.GetSandboxesSandboxIDMetrics500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

// ---------------------------------------------------------------------------
// Templates (SandboxPools)
// ---------------------------------------------------------------------------

func (s *Server) GetTemplates(ctx context.Context, _ e2bgen.GetTemplatesRequestObject) (e2bgen.GetTemplatesResponseObject, error) {
	if s.k8sClient == nil {
		return e2bgen.GetTemplates500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errResp("k8s client not available"))}, nil
	}

	auth := authFrom(ctx)
	poolList := &agentsv1alpha1.SandboxPoolList{}
	if err := s.k8sClient.List(ctx, poolList, client.InNamespace(auth.Namespace)); err != nil {
		return e2bgen.GetTemplates500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespServer(ctx, err, err.Error()))}, nil
	}

	templates := make(e2bgen.GetTemplates200JSONResponse, 0, len(poolList.Items))
	for i := range poolList.Items {
		templates = append(templates, poolToE2BTemplate(&poolList.Items[i]))
	}
	return templates, nil
}

func (s *Server) GetTemplatesTemplateID(ctx context.Context, req e2bgen.GetTemplatesTemplateIDRequestObject) (e2bgen.GetTemplatesTemplateIDResponseObject, error) {
	if s.k8sClient == nil {
		return e2bgen.GetTemplatesTemplateID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errResp("k8s client not available"))}, nil
	}

	auth := authFrom(ctx)
	pool := &agentsv1alpha1.SandboxPool{}
	if err := s.k8sClient.Get(ctx, client.ObjectKey{Namespace: auth.Namespace, Name: string(req.TemplateID)}, pool); err != nil {
		if errors.IsNotFound(err) {
			return e2bgen.GetTemplatesTemplateID401JSONResponse{N401JSONResponse: e2bgen.N401JSONResponse(errRespCode(404, "template not found"))}, nil
		}
		return e2bgen.GetTemplatesTemplateID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespServer(ctx, err, err.Error()))}, nil
	}

	// GetTemplatesTemplateID200JSONResponse is TemplateWithBuilds (not a wrapper)
	// TemplateWithBuilds has its own fields, not a Template subfield
	tmpl := poolToE2BTemplate(pool)
	result := e2bgen.TemplateWithBuilds{
		TemplateID: tmpl.TemplateID,
		Public:     tmpl.Public,
		SpawnCount: tmpl.SpawnCount,
		Aliases:    tmpl.Aliases,
		Names:      tmpl.Names,
		CreatedAt:  tmpl.CreatedAt,
		UpdatedAt:  tmpl.UpdatedAt,
		Builds:     []e2bgen.TemplateBuild{},
	}
	return e2bgen.GetTemplatesTemplateID200JSONResponse(result), nil
}

// poolToE2BTemplate converts an AgentBox SandboxPool to an E2B Template.
func poolToE2BTemplate(pool *agentsv1alpha1.SandboxPool) e2bgen.Template {
	return e2bdomain.ToE2BTemplate(pool)
}

// ---------------------------------------------------------------------------
// API Keys
// ---------------------------------------------------------------------------

func (s *Server) GetApiKeys(ctx context.Context, _ e2bgen.GetApiKeysRequestObject) (e2bgen.GetApiKeysResponseObject, error) {
	auth := authFrom(ctx)
	result, appErr := s.apikey.ListByTeamAndUser(ctx, auth.Team, auth.User)
	if appErr != nil {
		return e2bgen.GetApiKeys500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	keys := make(e2bgen.GetApiKeys200JSONResponse, 0, len(result.Items))
	for _, item := range result.Items {
		k := e2bgen.TeamAPIKey{
			Name:      item.Description,
			CreatedAt: item.IssuedAt,
			Mask: e2bgen.IdentifierMaskingDetails{
				Prefix:      item.ShortName,
				ValueLength: 16,
			},
		}
		keys = append(keys, k)
	}
	return keys, nil
}

func (s *Server) PostApiKeys(ctx context.Context, req e2bgen.PostApiKeysRequestObject) (e2bgen.PostApiKeysResponseObject, error) {
	if req.Body == nil {
		return e2bgen.PostApiKeys401JSONResponse{N401JSONResponse: e2bgen.N401JSONResponse(errRespCode(400, "request body required"))}, nil
	}

	auth := authFrom(ctx)
	result, appErr := s.apikey.Create(ctx, apidomain.CreateAPIKeyInput{
		Namespace:   auth.Namespace,
		User:        auth.User,
		Team:        auth.Team,
		Description: req.Body.Name,
	})
	if appErr != nil {
		return e2bgen.PostApiKeys500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	resp := e2bgen.CreatedTeamAPIKey{
		Name:      req.Body.Name,
		Key:       result.RawToken,
		CreatedAt: result.IssuedAt,
		Mask: e2bgen.IdentifierMaskingDetails{
			Prefix:      result.KeyID,
			ValueLength: 16,
		},
	}
	return e2bgen.PostApiKeys201JSONResponse(resp), nil
}

func (s *Server) DeleteApiKeysApiKeyID(ctx context.Context, req e2bgen.DeleteApiKeysApiKeyIDRequestObject) (e2bgen.DeleteApiKeysApiKeyIDResponseObject, error) {
	appErr := s.apikey.Delete(ctx, apidomain.DeleteAPIKeyInput{KeyID: string(req.ApiKeyID)})
	if appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.DeleteApiKeysApiKeyID404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.DeleteApiKeysApiKeyID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}
	return e2bgen.DeleteApiKeysApiKeyID204Response{}, nil
}

func (s *Server) PatchApiKeysApiKeyID(_ context.Context, _ e2bgen.PatchApiKeysApiKeyIDRequestObject) (e2bgen.PatchApiKeysApiKeyIDResponseObject, error) {
	return e2bgen.PatchApiKeysApiKeyID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

// ---------------------------------------------------------------------------
// All other operations return 501 Not Implemented
// ---------------------------------------------------------------------------

func (s *Server) PostAccessTokens(_ context.Context, _ e2bgen.PostAccessTokensRequestObject) (e2bgen.PostAccessTokensResponseObject, error) {
	return e2bgen.PostAccessTokens500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) DeleteAccessTokensAccessTokenID(_ context.Context, _ e2bgen.DeleteAccessTokensAccessTokenIDRequestObject) (e2bgen.DeleteAccessTokensAccessTokenIDResponseObject, error) {
	return e2bgen.DeleteAccessTokensAccessTokenID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostAdminTeamsTeamIDBuildsCancel(_ context.Context, _ e2bgen.PostAdminTeamsTeamIDBuildsCancelRequestObject) (e2bgen.PostAdminTeamsTeamIDBuildsCancelResponseObject, error) {
	return e2bgen.PostAdminTeamsTeamIDBuildsCancel500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostAdminTeamsTeamIDSandboxesKill(_ context.Context, _ e2bgen.PostAdminTeamsTeamIDSandboxesKillRequestObject) (e2bgen.PostAdminTeamsTeamIDSandboxesKillResponseObject, error) {
	return e2bgen.PostAdminTeamsTeamIDSandboxesKill500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetNodes(_ context.Context, _ e2bgen.GetNodesRequestObject) (e2bgen.GetNodesResponseObject, error) {
	return e2bgen.GetNodes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetNodesNodeID(_ context.Context, _ e2bgen.GetNodesNodeIDRequestObject) (e2bgen.GetNodesNodeIDResponseObject, error) {
	return e2bgen.GetNodesNodeID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostNodesNodeID(_ context.Context, _ e2bgen.PostNodesNodeIDRequestObject) (e2bgen.PostNodesNodeIDResponseObject, error) {
	return e2bgen.PostNodesNodeID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetSnapshots(_ context.Context, _ e2bgen.GetSnapshotsRequestObject) (e2bgen.GetSnapshotsResponseObject, error) {
	return e2bgen.GetSnapshots500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetTeams(_ context.Context, _ e2bgen.GetTeamsRequestObject) (e2bgen.GetTeamsResponseObject, error) {
	return e2bgen.GetTeams500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetTeamsTeamIDMetrics(_ context.Context, _ e2bgen.GetTeamsTeamIDMetricsRequestObject) (e2bgen.GetTeamsTeamIDMetricsResponseObject, error) {
	return e2bgen.GetTeamsTeamIDMetrics500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetTeamsTeamIDMetricsMax(_ context.Context, _ e2bgen.GetTeamsTeamIDMetricsMaxRequestObject) (e2bgen.GetTeamsTeamIDMetricsMaxResponseObject, error) {
	return e2bgen.GetTeamsTeamIDMetricsMax500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostTemplates(_ context.Context, _ e2bgen.PostTemplatesRequestObject) (e2bgen.PostTemplatesResponseObject, error) {
	return e2bgen.PostTemplates500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetTemplatesAliasesAlias(_ context.Context, _ e2bgen.GetTemplatesAliasesAliasRequestObject) (e2bgen.GetTemplatesAliasesAliasResponseObject, error) {
	return e2bgen.GetTemplatesAliasesAlias500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) DeleteTemplatesTags(_ context.Context, _ e2bgen.DeleteTemplatesTagsRequestObject) (e2bgen.DeleteTemplatesTagsResponseObject, error) {
	return e2bgen.DeleteTemplatesTags500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostTemplatesTags(_ context.Context, _ e2bgen.PostTemplatesTagsRequestObject) (e2bgen.PostTemplatesTagsResponseObject, error) {
	return e2bgen.PostTemplatesTags500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) DeleteTemplatesTemplateID(_ context.Context, _ e2bgen.DeleteTemplatesTemplateIDRequestObject) (e2bgen.DeleteTemplatesTemplateIDResponseObject, error) {
	return e2bgen.DeleteTemplatesTemplateID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PatchTemplatesTemplateID(_ context.Context, _ e2bgen.PatchTemplatesTemplateIDRequestObject) (e2bgen.PatchTemplatesTemplateIDResponseObject, error) {
	return e2bgen.PatchTemplatesTemplateID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostTemplatesTemplateID(_ context.Context, _ e2bgen.PostTemplatesTemplateIDRequestObject) (e2bgen.PostTemplatesTemplateIDResponseObject, error) {
	return e2bgen.PostTemplatesTemplateID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostTemplatesTemplateIDBuildsBuildID(_ context.Context, _ e2bgen.PostTemplatesTemplateIDBuildsBuildIDRequestObject) (e2bgen.PostTemplatesTemplateIDBuildsBuildIDResponseObject, error) {
	return e2bgen.PostTemplatesTemplateIDBuildsBuildID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetTemplatesTemplateIDBuildsBuildIDLogs(_ context.Context, _ e2bgen.GetTemplatesTemplateIDBuildsBuildIDLogsRequestObject) (e2bgen.GetTemplatesTemplateIDBuildsBuildIDLogsResponseObject, error) {
	return e2bgen.GetTemplatesTemplateIDBuildsBuildIDLogs500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetTemplatesTemplateIDBuildsBuildIDStatus(_ context.Context, _ e2bgen.GetTemplatesTemplateIDBuildsBuildIDStatusRequestObject) (e2bgen.GetTemplatesTemplateIDBuildsBuildIDStatusResponseObject, error) {
	return e2bgen.GetTemplatesTemplateIDBuildsBuildIDStatus500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetTemplatesTemplateIDFilesHash(_ context.Context, _ e2bgen.GetTemplatesTemplateIDFilesHashRequestObject) (e2bgen.GetTemplatesTemplateIDFilesHashResponseObject, error) {
	return e2bgen.GetTemplatesTemplateIDFilesHash500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetTemplatesTemplateIDTags(_ context.Context, _ e2bgen.GetTemplatesTemplateIDTagsRequestObject) (e2bgen.GetTemplatesTemplateIDTagsResponseObject, error) {
	return e2bgen.GetTemplatesTemplateIDTags500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetV2Sandboxes(_ context.Context, _ e2bgen.GetV2SandboxesRequestObject) (e2bgen.GetV2SandboxesResponseObject, error) {
	return e2bgen.GetV2Sandboxes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetV2SandboxesSandboxIDLogs(_ context.Context, _ e2bgen.GetV2SandboxesSandboxIDLogsRequestObject) (e2bgen.GetV2SandboxesSandboxIDLogsResponseObject, error) {
	return e2bgen.GetV2SandboxesSandboxIDLogs500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostV2Templates(_ context.Context, _ e2bgen.PostV2TemplatesRequestObject) (e2bgen.PostV2TemplatesResponseObject, error) {
	return e2bgen.PostV2Templates500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PatchV2TemplatesTemplateID(_ context.Context, _ e2bgen.PatchV2TemplatesTemplateIDRequestObject) (e2bgen.PatchV2TemplatesTemplateIDResponseObject, error) {
	return e2bgen.PatchV2TemplatesTemplateID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostV2TemplatesTemplateIDBuildsBuildID(_ context.Context, _ e2bgen.PostV2TemplatesTemplateIDBuildsBuildIDRequestObject) (e2bgen.PostV2TemplatesTemplateIDBuildsBuildIDResponseObject, error) {
	return e2bgen.PostV2TemplatesTemplateIDBuildsBuildID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostV3Templates(_ context.Context, _ e2bgen.PostV3TemplatesRequestObject) (e2bgen.PostV3TemplatesResponseObject, error) {
	return e2bgen.PostV3Templates500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetVolumes(_ context.Context, _ e2bgen.GetVolumesRequestObject) (e2bgen.GetVolumesResponseObject, error) {
	return e2bgen.GetVolumes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) PostVolumes(_ context.Context, _ e2bgen.PostVolumesRequestObject) (e2bgen.PostVolumesResponseObject, error) {
	return e2bgen.PostVolumes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) DeleteVolumesVolumeID(_ context.Context, _ e2bgen.DeleteVolumesVolumeIDRequestObject) (e2bgen.DeleteVolumesVolumeIDResponseObject, error) {
	return e2bgen.DeleteVolumesVolumeID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}

func (s *Server) GetVolumesVolumeID(_ context.Context, _ e2bgen.GetVolumesVolumeIDRequestObject) (e2bgen.GetVolumesVolumeIDResponseObject, error) {
	return e2bgen.GetVolumesVolumeID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(notImplemented())}, nil
}
