// Copyright 2026 ScitiX
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package handlers implements the E2B-compatible StrictServerInterface generated by oapi-codegen.
// Supported operations delegate to the AgentBox service layer; unsupported operations return 501.
package handlers

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"sigs.k8s.io/controller-runtime/pkg/client"

	"k8s.io/apimachinery/pkg/api/errors"

	agentsv1alpha1 "github.com/scitix/agent-sandbox/api/v1alpha1"
	apidomain "github.com/scitix/agent-sandbox/pkg/apiserver/domain"
	gen "github.com/scitix/agent-sandbox/pkg/apiserver/gen"
	"github.com/scitix/agent-sandbox/pkg/apiserver/service"
	"github.com/scitix/agent-sandbox/pkg/apiserver/service/federation"
	"github.com/scitix/agent-sandbox/pkg/controllers/sandboxpool/poststarthooks"
	e2bdomain "github.com/scitix/agent-sandbox/pkg/e2bcompat/domain"
	e2bgen "github.com/scitix/agent-sandbox/pkg/e2bcompat/gen"
	"github.com/scitix/agent-sandbox/pkg/utils/cluster"
	"github.com/scitix/agent-sandbox/pkg/utils/httpctx"
	"github.com/scitix/agent-sandbox/pkg/utils/httplog"
	"github.com/scitix/agent-sandbox/pkg/utils/logclient"
	"github.com/scitix/agent-sandbox/pkg/utils/promclient"
)

// Services bundles service dependencies for E2B handlers.
type Services struct {
	Sandbox service.SandboxService
	APIKey  service.APIKeyService
	// Vault serves the /secrets endpoints. Nil leaves them answering 501, so a
	// deployment without a vault behaves as it did before rather than
	// pretending to have an empty one.
	Vault service.VaultService
	// Federation exposes other clusters' Env capacity for the template listing.
	// Nil lists only this cluster's Envs.
	Federation *federation.Registry
	// LocalClusterID identifies this cluster in federation records.
	LocalClusterID string
	// Metrics queries the cluster's metrics backend. Nil disables the metrics
	// endpoints.
	Metrics *promclient.Client
	// MetricsSelector returns the PromQL label matcher for this cluster. Nil
	// means no cluster scoping, which is only correct for a backend that serves
	// a single cluster.
	MetricsSelector func() string
	// CentralLogs reads finished sandboxes' output. Nil limits logs to live
	// sandboxes.
	CentralLogs *logclient.Client
	// LogFilters scopes central-log queries to this cluster.
	LogFilters func() map[string]string
	// Forwarder enables cross-cluster forwarding via E2B API.
	// localClusterID is embedded in the forwarder itself; no separate field needed.
	// When Forwarder is nil, cross-cluster requests will be rejected.
	Forwarder *service.CrossClusterForwarder
}

// Server implements e2bgen.StrictServerInterface.
// Supported: GET/POST /sandboxes, GET/DELETE /sandboxes/:id, POST /sandboxes/:id/timeout,
//
//	GET /templates, GET /templates/:id, GET/POST/DELETE /api-keys, GET /health
//
// Every other operation answers 501 with a message naming the alternative;
// see unsupported.go.
type Server struct {
	sandbox service.SandboxService
	apikey  service.APIKeyService
	vault   service.VaultService
	// federation carries every cluster's per-Env capacity, already streamed in
	// by the sync layer. It is what lets the template listing include other
	// clusters' Envs without a fan-out query. May be nil.
	federation     *federation.Registry
	localClusterID string
	// metrics queries the cluster's metrics backend for per-sandbox usage. Nil
	// or unconfigured leaves the metrics endpoints answering 501 rather than
	// an empty series, which would read as "this sandbox is idle".
	metrics *promclient.Client
	// metricsSelector returns the PromQL label matcher identifying this cluster
	// in a shared backend, e.g. `cluster="foo"`. It is a function rather than a
	// string because the value arrives on the cluster-config stream and can
	// change while the process runs.
	metricsSelector func() string
	// centralLogs reads a finished sandbox's output, whose Pod no longer
	// exists. Nil means only live sandboxes can be asked for logs.
	centralLogs *logclient.Client
	// logFilters scopes a central-log query to this cluster; same liveness
	// reasoning as metricsSelector.
	logFilters    func() map[string]string
	k8sClient     client.Client
	gatewayDomain string
	forwarder     *service.CrossClusterForwarder
}

// NewServer creates a new E2B handler Server.
func NewServer(svcs Services, k8sClient client.Client, gatewayDomain string) *Server {
	return &Server{
		sandbox:         svcs.Sandbox,
		apikey:          svcs.APIKey,
		vault:           svcs.Vault,
		federation:      svcs.Federation,
		localClusterID:  svcs.LocalClusterID,
		metrics:         svcs.Metrics,
		metricsSelector: svcs.MetricsSelector,
		centralLogs:     svcs.CentralLogs,
		logFilters:      svcs.LogFilters,
		k8sClient:       k8sClient,
		gatewayDomain:   gatewayDomain,
		forwarder:       svcs.Forwarder,
	}
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

// authFrom extracts AuthInfo from the context.
// Works with both raw *gin.Context and wrapped contexts.
func authFrom(ctx context.Context) apidomain.AuthInfo {
	return httpctx.AuthFrom(ctx)
}

// errRespAppErr converts an AppError from the service layer to an E2B-shaped
// error body. It also emits a structured klog entry via httplog so 5xx
// responses always have a matching server-side log line.
func errRespAppErr(ctx context.Context, appErr *apidomain.AppError) e2bgen.Error {
	httplog.LogAppError(httpctx.GinFromCtx(ctx), appErr)
	return e2bgen.Error{Code: int32(appErr.Code), Message: appErr.Message}
}

// errResp is retained for places that only have a string message (no
// AppError). Callers that have a non-nil underlying cause should prefer
// errRespServer so the cause is logged.
func errResp(msg string) e2bgen.Error {
	return e2bgen.Error{Code: 500, Message: msg}
}

// errRespServer logs a server-side (5xx) error that did not go through the
// AppError abstraction and returns the E2B error body.
func errRespServer(ctx context.Context, cause error, msg string) e2bgen.Error {
	httplog.LogServerError(httpctx.GinFromCtx(ctx), cause, msg)
	return e2bgen.Error{Code: 500, Message: msg}
}

func errRespCode(code int32, msg string) e2bgen.Error {
	return e2bgen.Error{Code: code, Message: msg}
}

// jsonBody marshals v to JSON and returns it as an io.Reader.
// Used when forwarding cross-cluster requests whose body has already been
// consumed by the strict-server framework.
func jsonBody(v any) io.Reader {
	b, err := json.Marshal(v)
	if err != nil {
		return nil
	}
	return bytes.NewReader(b)
}

// isCrossCluster reports whether clusterID refers to a remote cluster.
// Delegates to the forwarder's nil-safe IsCrossCluster.
func (s *Server) isCrossCluster(clusterID string) bool {
	return s.forwarder.IsCrossCluster(clusterID)
}

// loadPool fetches a SandboxPool from K8s. Returns nil on error/missing.
func (s *Server) loadPool(ctx context.Context, namespace, poolName string) *agentsv1alpha1.SandboxPool {
	if s.k8sClient == nil || poolName == "" {
		return nil
	}
	pool := &agentsv1alpha1.SandboxPool{}
	if err := s.k8sClient.Get(ctx, client.ObjectKey{Namespace: namespace, Name: poolName}, pool); err != nil {
		return nil
	}
	return pool
}

// loadPoolMap fetches all SandboxPools in a namespace as a map keyed by name.
func (s *Server) loadPoolMap(ctx context.Context, namespace string) map[string]*agentsv1alpha1.SandboxPool {
	if s.k8sClient == nil {
		return nil
	}
	poolList := &agentsv1alpha1.SandboxPoolList{}
	if err := s.k8sClient.List(ctx, poolList, client.InNamespace(namespace)); err != nil {
		return nil
	}
	m := make(map[string]*agentsv1alpha1.SandboxPool, len(poolList.Items))
	for i := range poolList.Items {
		m[poolList.Items[i].Name] = &poolList.Items[i]
	}
	return m
}

// domainSandboxToE2BSandbox converts a native gen.Sandbox to an E2B Sandbox response.
func (s *Server) domainSandboxToE2BSandbox(ctx context.Context, sb *gen.Sandbox, namespace string) e2bgen.Sandbox {
	pool := s.loadPool(ctx, namespace, sb.PoolName)
	return e2bdomain.ToE2BSandbox(sb, pool, s.gatewayDomain)
}

// domainSandboxToSandboxDetail converts a native gen.Sandbox to an E2B SandboxDetail.
func (s *Server) domainSandboxToSandboxDetail(ctx context.Context, sb *gen.Sandbox, namespace string) e2bgen.SandboxDetail {
	pool := s.loadPool(ctx, namespace, sb.PoolName)
	return e2bdomain.ToE2BSandboxDetail(sb, pool, s.gatewayDomain)
}

// domainSandboxToListedSandbox converts a native gen.Sandbox to an E2B ListedSandbox.
func domainSandboxToListedSandbox(sb *gen.Sandbox, pool *agentsv1alpha1.SandboxPool) e2bgen.ListedSandbox {
	return e2bdomain.ToE2BListedSandbox(sb, pool)
}

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------

func (s *Server) GetHealth(_ context.Context, _ e2bgen.GetHealthRequestObject) (e2bgen.GetHealthResponseObject, error) {
	return e2bgen.GetHealth204Response{}, nil
}

// ---------------------------------------------------------------------------
// Sandboxes
// ---------------------------------------------------------------------------

// imageOverrideMetaKey is the reserved metadata key used to override the sandbox main container image
// via the E2B-compatible API. This key is consumed internally and will NOT be forwarded to sandbox metadata.
const imageOverrideMetaKey = "agentbox.scitix.ai/image"

// startupTimeoutMetaKey is the reserved metadata key used to override the sandbox startup timeout
// via the E2B-compatible API. Value is in seconds (integer string). This key is consumed internally
// and will NOT be forwarded to sandbox metadata.
const startupTimeoutMetaKey = "agentbox.scitix.ai/startup-timeout"

// allowPrivateNetworksMetaKey opens the private ranges (RFC1918, CGNAT, ULA)
// wholesale for this sandbox. Accepted values are "true" and "1"; anything else
// leaves the baseline on. Consumed here and NOT forwarded to sandbox metadata.
//
// Rarely needed: listing an internal host or CIDR in network.allowOut already
// reaches it. This is for "allow everything, the cluster network included",
// which network.allowOut ["*"] deliberately does not mean.
//
// It rides on metadata because E2B's SandboxNetworkConfig has no field for it
// and inventing one would be a dialect. It never opens the cloud-metadata or
// link-local ranges — nothing does.
const allowPrivateNetworksMetaKey = "agentbox.scitix.ai/allow-private-networks"

// consumeReservedMetadata applies the reserved metadata keys to input and
// removes them from input.Metadata, so they configure the sandbox rather than
// being stored as its own metadata and echoed back on every read.
//
// Returns whether the request asked to lift the anti-SSRF baseline. That one is
// returned rather than written onto input because it belongs to the network
// policy, which is parsed further down from a different part of the body.
func consumeReservedMetadata(input *service.CreateSandboxInput) bool {
	// Image override: takes priority over the "poolName//image" syntax.
	if img, ok := input.Metadata[imageOverrideMetaKey]; ok && img != "" {
		input.Image = img
		delete(input.Metadata, imageOverrideMetaKey)
	}
	// Startup timeout, in seconds.
	if raw, ok := input.Metadata[startupTimeoutMetaKey]; ok && raw != "" {
		if secs, err := strconv.Atoi(raw); err == nil && secs > 0 {
			input.StartupTimeout = time.Duration(secs) * time.Second
		}
		delete(input.Metadata, startupTimeoutMetaKey)
	}
	// Scaling-group placement: pin this create to a specific autoscaling group
	// (e.g. "1c2Gi") so it only lands on member pools in that group.
	if grp, ok := input.Metadata[service.MetaKeyScalingGroup]; ok && grp != "" {
		input.RequestedScalingGroup = grp
		delete(input.Metadata, service.MetaKeyScalingGroup)
	}
	allowPrivate := false
	if raw, ok := input.Metadata[allowPrivateNetworksMetaKey]; ok {
		allowPrivate = raw == "true" || raw == "1"
		delete(input.Metadata, allowPrivateNetworksMetaKey)
	}
	return allowPrivate
}

func (s *Server) PostSandboxes(ctx context.Context, req e2bgen.PostSandboxesRequestObject) (e2bgen.PostSandboxesResponseObject, error) {
	if req.Body == nil || strings.TrimSpace(req.Body.TemplateID) == "" {
		return e2bgen.PostSandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(errRespCode(400, "templateID is required"))}, nil
	}

	parsed := cluster.ParsePoolRef(req.Body.TemplateID)
	if parsed.PoolName == "" {
		return e2bgen.PostSandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(errRespCode(400, "templateID is required"))}, nil
	}

	// Refuse what we would otherwise silently drop, before anything is claimed.
	if e := rejectUnsupportedCreateFields(req.Body); e != nil {
		return e2bgen.PostSandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(*e)}, nil
	}

	auth := authFrom(ctx)
	allowPrivate := false
	input := service.CreateSandboxInput{
		ClusterID: parsed.ClusterID,
		PoolName:  parsed.PoolName,
		Namespace: auth.Namespace,
		User:      auth.User,
		Image:     parsed.ImageOverride, // Option B: image embedded via "poolName//image" syntax
	}
	if req.Body.Metadata != nil {
		input.Metadata = map[string]string(*req.Body.Metadata)
		allowPrivate = consumeReservedMetadata(&input)
	}
	if req.Body.EnvVars != nil && len(*req.Body.EnvVars) > 0 {
		input.PostStartHooks = []poststarthooks.Action{{
			HTTPPost: &poststarthooks.HTTPPostAction{
				Port: 49983,
				Path: "/init",
				Body: map[string]any{
					"envVars": map[string]string(*req.Body.EnvVars),
				},
			},
		}}
	}
	if req.Body.Timeout != nil && *req.Body.Timeout > 0 {
		input.IdleTimeout = time.Duration(*req.Body.Timeout) * time.Second
	}
	// Egress network policy: map E2B network / allow_internet_access onto the
	// AgentBox SandboxNetworkPolicy. Unsupported E2B features (SOCKS5 egress
	// proxy) are rejected rather than silently dropped — matching E2B's own
	// feature gating. The service layer rejects a request targeting an
	// environment whose gateway is off.
	np, vaultRules, npErr := parseE2BNetworkPolicy(req.Body)
	if npErr != nil {
		return e2bgen.PostSandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(*npErr)}, nil
	}
	if np != nil {
		np.AllowPrivateNetworks = allowPrivate
	}
	input.NetworkPolicy = np
	// Carried as a separate input rather than folded into NetworkPolicy: these
	// rules only become an injection block after every ${e2b.secrets.<name>}
	// reference has been resolved against the caller's own vault.
	input.VaultRules = vaultRules
	// Inject team/user from auth into labels so they are recorded on the pod
	// and metrics (agentbox_sandbox_create_total) carry the correct dimensions.
	input.Labels = make(map[string]string)
	if auth.Team != "" {
		input.Labels[agentsv1alpha1.LabelTeam] = auth.Team
	}
	if auth.User != "" {
		input.Labels[agentsv1alpha1.LabelUser] = auth.User
	}

	// Cross-cluster forwarding: if the template explicitly references a remote
	// cluster ("cluster::template"), forward the request to that cluster's E2B API.
	if s.isCrossCluster(input.ClusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), input.ClusterID, service.URLKindE2B, jsonBody(req.Body))
		return nil, nil
	}

	// Env-based cross-cluster placement: for a bare template name whose local
	// Env has no idle capacity, pin the foreign member pool and forward the
	// request rewritten as "cluster::pool" (preserving any image override), so
	// the receiver resolves a direct local pool and prefixes the sandbox ID.
	if parsed.ClusterID == "" {
		if r, ok := s.sandbox.(interface {
			ResolveCreateTarget(namespace, poolOrEnvName, scalingGroup string) (string, string, bool)
		}); ok {
			if tc, tp, found := r.ResolveCreateTarget(input.Namespace, parsed.PoolName, input.RequestedScalingGroup); found && s.isCrossCluster(tc) {
				ref := tc + "::" + tp
				if parsed.ImageOverride != "" {
					ref += "//" + parsed.ImageOverride
				}
				fwd := *req.Body
				fwd.TemplateID = ref
				s.forwarder.Forward(httpctx.GinFromCtx(ctx), tc, service.URLKindE2B, jsonBody(&fwd))
				return nil, nil
			}
		}
	}

	result, appErr := s.sandbox.Create(ctx, input)
	if appErr != nil {
		switch appErr.Code {
		// A missing Env reads as a bad templateID rather than a missing
		// resource: E2B's create has no 404, and the id came from the caller.
		case apidomain.ErrCodeNotFound, apidomain.ErrCodeBadRequest:
			return e2bgen.PostSandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(errRespCode(400, appErr.Message))}, nil
		// Capacity, not correctness: retrying the identical request can succeed
		// once a pool has an idle Pod again, which 500 would not tell a client.
		case apidomain.ErrCodeServiceUnavailable:
			return e2bgen.PostSandboxes503JSONResponse{N503JSONResponse: e2bgen.N503JSONResponse(errRespAppErr(ctx, appErr))}, nil
		case apidomain.ErrCodeGatewayTimeout:
			return e2bgen.PostSandboxes504JSONResponse{N504JSONResponse: e2bgen.N504JSONResponse(errRespAppErr(ctx, appErr))}, nil
		default:
			return e2bgen.PostSandboxes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
		}
	}

	sb := s.domainSandboxToE2BSandbox(ctx, result, auth.Namespace)
	return e2bgen.PostSandboxes201JSONResponse(sb), nil
}

func (s *Server) GetSandboxes(ctx context.Context, _ e2bgen.GetSandboxesRequestObject) (e2bgen.GetSandboxesResponseObject, error) {
	auth := authFrom(ctx)
	result, appErr := s.sandbox.List(ctx, service.SandboxListFilter{
		Namespace: auth.Namespace,
		Team:      auth.Team,
		User:      auth.User,
		Limit:     0,
	})
	if appErr != nil {
		return e2bgen.GetSandboxes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	poolMap := s.loadPoolMap(ctx, auth.Namespace)

	items := make([]e2bgen.ListedSandbox, 0, len(result.Items))
	for i := range result.Items {
		sb := &result.Items[i]
		// The native listing merges terminated sandboxes in from the history store
		// and the E2B state enum has no way to say "finished", so they are dropped
		// rather than reported as running. History lives on the native API.
		if !e2bdomain.IsLive(sb) {
			continue
		}
		pool := poolMap[sb.PoolName]
		items = append(items, domainSandboxToListedSandbox(sb, pool))
	}

	return e2bgen.GetSandboxes200JSONResponse(items), nil
}

func (s *Server) GetSandboxesSandboxID(ctx context.Context, req e2bgen.GetSandboxesSandboxIDRequestObject) (e2bgen.GetSandboxesSandboxIDResponseObject, error) {
	auth := authFrom(ctx)
	sandboxID := req.SandboxID
	if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, nil)
		return nil, nil
	}
	// GetLive, not Get: a SandboxDetail can only report `running`, so answering from
	// the history store would describe a reclaimed sandbox as usable. Upstream E2B
	// 404s a killed sandbox too; the native API is where its record stays readable.
	result, appErr := s.sandbox.GetLive(ctx, auth.Namespace, sandboxID)
	if appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.GetSandboxesSandboxID404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.GetSandboxesSandboxID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	detail := s.domainSandboxToSandboxDetail(ctx, result, auth.Namespace)
	return e2bgen.GetSandboxesSandboxID200JSONResponse(detail), nil
}

func (s *Server) DeleteSandboxesSandboxID(ctx context.Context, req e2bgen.DeleteSandboxesSandboxIDRequestObject) (e2bgen.DeleteSandboxesSandboxIDResponseObject, error) {
	auth := authFrom(ctx)
	sandboxID := req.SandboxID
	if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, nil)
		return nil, nil
	}
	_, appErr := s.sandbox.Delete(ctx, auth.Namespace, sandboxID)
	if appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.DeleteSandboxesSandboxID404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.DeleteSandboxesSandboxID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}
	return e2bgen.DeleteSandboxesSandboxID204Response{}, nil
}

func (s *Server) PostSandboxesSandboxIDTimeout(ctx context.Context, req e2bgen.PostSandboxesSandboxIDTimeoutRequestObject) (e2bgen.PostSandboxesSandboxIDTimeoutResponseObject, error) {
	if req.Body == nil || req.Body.Timeout <= 0 {
		// The spec declares no 400 here, but a bad argument must not surface as
		// an authentication failure — the caller would go and check its key.
		return statusJSON{status: http.StatusBadRequest,
			msg: "timeout must be a positive integer number of seconds"}, nil
	}

	auth := authFrom(ctx)
	sandboxID := req.SandboxID
	timeout := time.Duration(req.Body.Timeout) * time.Second
	if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, jsonBody(req.Body))
		return nil, nil
	}
	if appErr := s.sandbox.SetTimeout(ctx, auth.Namespace, sandboxID, timeout); appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.PostSandboxesSandboxIDTimeout404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.PostSandboxesSandboxIDTimeout500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}
	return e2bgen.PostSandboxesSandboxIDTimeout204Response{}, nil
}

func (s *Server) PostSandboxesSandboxIDRefreshes(ctx context.Context, req e2bgen.PostSandboxesSandboxIDRefreshesRequestObject) (e2bgen.PostSandboxesSandboxIDRefreshesResponseObject, error) {
	// Refreshes = extend idle timeout to keep the sandbox alive.
	if req.Body != nil && req.Body.Duration != nil && *req.Body.Duration > 0 {
		auth := authFrom(ctx)
		sandboxID := req.SandboxID
		timeout := time.Duration(*req.Body.Duration) * time.Second
		if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
			s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, jsonBody(req.Body))
			return nil, nil
		}
		if appErr := s.sandbox.SetTimeout(ctx, auth.Namespace, sandboxID, timeout); appErr != nil {
			if appErr.Code == apidomain.ErrCodeNotFound {
				return e2bgen.PostSandboxesSandboxIDRefreshes404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
			}
			return e2bgen.PostSandboxesSandboxIDRefreshes401JSONResponse{N401JSONResponse: e2bgen.N401JSONResponse(errRespCode(500, appErr.Message))}, nil
		}
	}
	return e2bgen.PostSandboxesSandboxIDRefreshes204Response{}, nil
}

// Not supported operations — return 501

func (s *Server) PostSandboxesSandboxIDPause(_ context.Context, _ e2bgen.PostSandboxesSandboxIDPauseRequestObject) (e2bgen.PostSandboxesSandboxIDPauseResponseObject, error) {
	return unsupportedOp("PostSandboxesSandboxIDPause", catArchitectural, msgPauseResume), nil
}

func (s *Server) PostSandboxesSandboxIDResume(_ context.Context, _ e2bgen.PostSandboxesSandboxIDResumeRequestObject) (e2bgen.PostSandboxesSandboxIDResumeResponseObject, error) {
	return unsupportedOp("PostSandboxesSandboxIDResume", catArchitectural, msgPauseResume), nil
}

func (s *Server) PostSandboxesSandboxIDSnapshots(_ context.Context, _ e2bgen.PostSandboxesSandboxIDSnapshotsRequestObject) (e2bgen.PostSandboxesSandboxIDSnapshotsResponseObject, error) {
	return unsupportedOp("PostSandboxesSandboxIDSnapshots", catArchitectural, msgSnapshots), nil
}

func (s *Server) PostSandboxesSandboxIDFork(_ context.Context, _ e2bgen.PostSandboxesSandboxIDForkRequestObject) (e2bgen.PostSandboxesSandboxIDForkResponseObject, error) {
	return unsupportedOp("PostSandboxesSandboxIDFork", catArchitectural, msgFork), nil
}

func (s *Server) GetAdminSandboxesRunningCounts(_ context.Context, _ e2bgen.GetAdminSandboxesRunningCountsRequestObject) (e2bgen.GetAdminSandboxesRunningCountsResponseObject, error) {
	return unsupportedOp("GetAdminSandboxesRunningCounts", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) GetV2Templates(_ context.Context, _ e2bgen.GetV2TemplatesRequestObject) (e2bgen.GetV2TemplatesResponseObject, error) {
	return unsupportedOp("GetV2Templates", catUnimplemented, msgTemplateListV2), nil
}

// PostSandboxesSandboxIDConnect re-attaches to a sandbox by ID, returning the
// same shape create does so an SDK can rebuild its handle from an ID alone.
//
// Upstream, connect resumes a *paused* sandbox. AgentBox has no pause — a
// sandbox is either running in its pool Pod or gone — so here it means "attach
// to a running one", and a sandbox that was killed or expired is a 404 (which
// the SDKs surface as sandbox-not-found).
//
// The timeout in the body is applied as upstream defines it: expiry becomes now
// plus that value, so it can move a deadline in either direction. Note that the
// SDKs default it (300s in Python), so a bare connect() shortens a sandbox that
// was created with a longer timeout — pass the timeout you want, or use
// POST /sandboxes/{id}/timeout to set one without re-attaching. A missing or
// non-positive value leaves the deadline alone rather than failing the attach.
func (s *Server) PostSandboxesSandboxIDConnect(ctx context.Context, req e2bgen.PostSandboxesSandboxIDConnectRequestObject) (e2bgen.PostSandboxesSandboxIDConnectResponseObject, error) {
	auth := authFrom(ctx)
	sandboxID := req.SandboxID
	if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, jsonBody(req.Body))
		return nil, nil
	}

	// GetLive, not Get: a reclaimed sandbox must 404 here so the SDK raises
	// sandbox-not-found. Get would answer from the history store, and the caller
	// would build a handle onto a sandbox that no longer exists.
	result, appErr := s.sandbox.GetLive(ctx, auth.Namespace, sandboxID)
	if appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.PostSandboxesSandboxIDConnect404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.PostSandboxesSandboxIDConnect500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	if req.Body != nil && req.Body.Timeout > 0 {
		timeout := time.Duration(req.Body.Timeout) * time.Second
		if tErr := s.sandbox.SetTimeout(ctx, auth.Namespace, sandboxID, timeout); tErr != nil {
			if tErr.Code == apidomain.ErrCodeNotFound {
				return e2bgen.PostSandboxesSandboxIDConnect404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, tErr.Message))}, nil
			}
			return e2bgen.PostSandboxesSandboxIDConnect500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, tErr))}, nil
		}
	}

	return e2bgen.PostSandboxesSandboxIDConnect200JSONResponse(s.domainSandboxToE2BSandbox(ctx, result, auth.Namespace)), nil
}

// ---------------------------------------------------------------------------
// Templates (SandboxPools)
// ---------------------------------------------------------------------------

func (s *Server) GetTemplates(ctx context.Context, _ e2bgen.GetTemplatesRequestObject) (e2bgen.GetTemplatesResponseObject, error) {
	if s.k8sClient == nil {
		return e2bgen.GetTemplates500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errResp("k8s client not available"))}, nil
	}

	auth := authFrom(ctx)
	local, err := s.listLocalTemplates(ctx, auth.Namespace)
	if err != nil {
		return e2bgen.GetTemplates500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespServer(ctx, err, err.Error()))}, nil
	}

	known := make(map[string]struct{}, len(local))
	for i := range local {
		known[local[i].TemplateID] = struct{}{}
	}

	templates := make(e2bgen.GetTemplates200JSONResponse, 0, len(local))
	templates = append(templates, local...)
	templates = append(templates, s.listForeignTemplates(auth.Namespace, known)...)
	return templates, nil
}

func (s *Server) GetTemplatesTemplateID(ctx context.Context, req e2bgen.GetTemplatesTemplateIDRequestObject) (e2bgen.GetTemplatesTemplateIDResponseObject, error) {
	if s.k8sClient == nil {
		return e2bgen.GetTemplatesTemplateID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errResp("k8s client not available"))}, nil
	}

	auth := authFrom(ctx)

	// An Env first, because that is what the create endpoint resolves a bare
	// name to. Falling back to a Pool keeps callers that still address a pool
	// by name working.
	env := &agentsv1alpha1.SandboxEnv{}
	if err := s.k8sClient.Get(ctx, client.ObjectKey{Namespace: auth.Namespace, Name: req.TemplateID}, env); err == nil {
		tmpl := templateFromEnv(env, memberPoolNames(env))
		return e2bgen.GetTemplatesTemplateID200JSONResponse{Body: e2bgen.TemplateWithBuilds{
			TemplateID: tmpl.TemplateID,
			Public:     tmpl.Public,
			SpawnCount: tmpl.SpawnCount,
			Aliases:    tmpl.Aliases,
			Names:      tmpl.Names,
			CreatedAt:  tmpl.CreatedAt,
			UpdatedAt:  tmpl.UpdatedAt,
			Builds:     []e2bgen.TemplateBuild{},
		}}, nil
	}

	pool := &agentsv1alpha1.SandboxPool{}
	if err := s.k8sClient.Get(ctx, client.ObjectKey{Namespace: auth.Namespace, Name: req.TemplateID}, pool); err != nil {
		if errors.IsNotFound(err) {
			// Answering a missing template through the 401 response type made
			// the SDK raise an authentication error, sending callers off to
			// rotate a perfectly good API key.
			return statusJSON{status: http.StatusNotFound,
				msg: "template not found: pass a SandboxEnv name (GET /templates lists them)"}, nil
		}
		return e2bgen.GetTemplatesTemplateID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespServer(ctx, err, err.Error()))}, nil
	}

	// GetTemplatesTemplateID200JSONResponse carries the body plus an optional
	// X-Next-Token pagination header; there is no next page for a single template.
	// TemplateWithBuilds has its own fields, not a Template subfield
	tmpl := poolToE2BTemplate(pool)
	result := e2bgen.TemplateWithBuilds{
		TemplateID: tmpl.TemplateID,
		Public:     tmpl.Public,
		SpawnCount: tmpl.SpawnCount,
		Aliases:    tmpl.Aliases,
		Names:      tmpl.Names,
		CreatedAt:  tmpl.CreatedAt,
		UpdatedAt:  tmpl.UpdatedAt,
		Builds:     []e2bgen.TemplateBuild{},
	}
	return e2bgen.GetTemplatesTemplateID200JSONResponse{Body: result}, nil
}

// poolToE2BTemplate converts an AgentBox SandboxPool to an E2B Template.
func poolToE2BTemplate(pool *agentsv1alpha1.SandboxPool) e2bgen.Template {
	return e2bdomain.ToE2BTemplate(pool)
}

// ---------------------------------------------------------------------------
// API Keys
// ---------------------------------------------------------------------------

func (s *Server) GetApiKeys(ctx context.Context, _ e2bgen.GetApiKeysRequestObject) (e2bgen.GetApiKeysResponseObject, error) {
	auth := authFrom(ctx)
	items, appErr := s.apikey.ListByTeamAndUser(ctx, auth.Team, auth.User)
	if appErr != nil {
		return e2bgen.GetApiKeys500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	keys := make(e2bgen.GetApiKeys200JSONResponse, 0, len(items))
	for _, item := range items {
		k := e2bgen.TeamAPIKey{
			Name:      item.Description,
			CreatedAt: item.IssuedAt,
			Mask: e2bgen.IdentifierMaskingDetails{
				Prefix:      item.ShortName,
				ValueLength: 16,
			},
		}
		keys = append(keys, k)
	}
	return keys, nil
}

func (s *Server) PostApiKeys(ctx context.Context, req e2bgen.PostApiKeysRequestObject) (e2bgen.PostApiKeysResponseObject, error) {
	if req.Body == nil {
		return statusJSON{status: http.StatusBadRequest, msg: "request body required"}, nil
	}

	auth := authFrom(ctx)
	result, appErr := s.apikey.Create(ctx, service.CreateAPIKeyInput{
		Namespace:   auth.Namespace,
		User:        auth.User,
		Team:        auth.Team,
		Description: req.Body.Name,
	})
	if appErr != nil {
		return e2bgen.PostApiKeys500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	resp := e2bgen.CreatedTeamAPIKey{
		Name:      req.Body.Name,
		Key:       result.RawToken,
		CreatedAt: result.IssuedAt,
		Mask: e2bgen.IdentifierMaskingDetails{
			Prefix:      result.KeyID,
			ValueLength: 16,
		},
	}
	return e2bgen.PostApiKeys201JSONResponse(resp), nil
}

func (s *Server) DeleteApiKeysApiKeyID(ctx context.Context, req e2bgen.DeleteApiKeysApiKeyIDRequestObject) (e2bgen.DeleteApiKeysApiKeyIDResponseObject, error) {
	appErr := s.apikey.Delete(ctx, req.ApiKeyID)
	if appErr != nil {
		if appErr.Code == apidomain.ErrCodeNotFound {
			return e2bgen.DeleteApiKeysApiKeyID404JSONResponse{N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		}
		return e2bgen.DeleteApiKeysApiKeyID500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}
	return e2bgen.DeleteApiKeysApiKeyID204Response{}, nil
}

func (s *Server) PatchApiKeysApiKeyID(_ context.Context, _ e2bgen.PatchApiKeysApiKeyIDRequestObject) (e2bgen.PatchApiKeysApiKeyIDResponseObject, error) {
	return unsupportedOp("PatchApiKeysApiKeyID", catUnimplemented, msgAPIKeyRename), nil
}

// ---------------------------------------------------------------------------
// All other operations return 501 Not Implemented
// ---------------------------------------------------------------------------

func (s *Server) PostAccessTokens(_ context.Context, _ e2bgen.PostAccessTokensRequestObject) (e2bgen.PostAccessTokensResponseObject, error) {
	return unsupportedOp("PostAccessTokens", catArchitectural, msgAccessTokens), nil
}

func (s *Server) DeleteAccessTokensAccessTokenID(_ context.Context, _ e2bgen.DeleteAccessTokensAccessTokenIDRequestObject) (e2bgen.DeleteAccessTokensAccessTokenIDResponseObject, error) {
	return unsupportedOp("DeleteAccessTokensAccessTokenID", catArchitectural, msgAccessTokens), nil
}

func (s *Server) PostAdminTeamsTeamIDBuildsCancel(_ context.Context, _ e2bgen.PostAdminTeamsTeamIDBuildsCancelRequestObject) (e2bgen.PostAdminTeamsTeamIDBuildsCancelResponseObject, error) {
	return unsupportedOp("PostAdminTeamsTeamIDBuildsCancel", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) PostAdminTeamsTeamIDApiKeys(_ context.Context, _ e2bgen.PostAdminTeamsTeamIDApiKeysRequestObject) (e2bgen.PostAdminTeamsTeamIDApiKeysResponseObject, error) {
	return unsupportedOp("PostAdminTeamsTeamIDApiKeys", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) DeleteAdminTeamsTeamIDApiKeysApiKeyID(_ context.Context, _ e2bgen.DeleteAdminTeamsTeamIDApiKeysApiKeyIDRequestObject) (e2bgen.DeleteAdminTeamsTeamIDApiKeysApiKeyIDResponseObject, error) {
	return unsupportedOp("DeleteAdminTeamsTeamIDApiKeysApiKeyID", catArchitectural, msgClusterAdmin), nil
}

// networkUpdateBadRequest carries a 400 for the live-network update, which E2B's
// spec does not declare a 400 for — the generator therefore emits no response
// type for it. A rejected body is still a client error and has to say so, so the
// status is written directly rather than dressed up as one of the declared ones.
type networkUpdateBadRequest struct{ err e2bgen.Error }

func (r networkUpdateBadRequest) VisitPutSandboxesSandboxIDNetworkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusBadRequest)
	return json.NewEncoder(w).Encode(r.err)
}

// PutSandboxesSandboxIDNetwork replaces a running sandbox's egress filtering.
// Per E2B's contract the body is a full replacement: an omitted field clears it,
// so an empty body means "unrestricted" rather than "leave as it was".
func (s *Server) PutSandboxesSandboxIDNetwork(ctx context.Context, req e2bgen.PutSandboxesSandboxIDNetworkRequestObject) (e2bgen.PutSandboxesSandboxIDNetworkResponseObject, error) {
	auth := authFrom(ctx)
	sandboxID := req.SandboxID
	if clusterID, _ := cluster.SplitSandboxID(sandboxID); s.isCrossCluster(clusterID) {
		s.forwarder.Forward(httpctx.GinFromCtx(ctx), clusterID, service.URLKindE2B, nil)
		return nil, nil
	}

	np, npErr := parseE2BNetworkUpdate(req.Body)
	if npErr != nil {
		return networkUpdateBadRequest{err: *npErr}, nil
	}

	if appErr := s.sandbox.UpdateSandboxNetwork(ctx, auth.Namespace, sandboxID, np); appErr != nil {
		switch appErr.Code {
		case apidomain.ErrCodeNotFound:
			return e2bgen.PutSandboxesSandboxIDNetwork404JSONResponse{
				N404JSONResponse: e2bgen.N404JSONResponse(errRespCode(404, appErr.Message))}, nil
		case apidomain.ErrCodeConflict:
			return e2bgen.PutSandboxesSandboxIDNetwork409JSONResponse{
				N409JSONResponse: e2bgen.N409JSONResponse(errRespCode(409, appErr.Message))}, nil
		case apidomain.ErrCodeBadRequest:
			return networkUpdateBadRequest{err: errRespCode(400, appErr.Message)}, nil
		default:
			return e2bgen.PutSandboxesSandboxIDNetwork500JSONResponse{
				N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
		}
	}
	return e2bgen.PutSandboxesSandboxIDNetwork204Response{}, nil
}

func (s *Server) PostAdminTeamsTeamIDSandboxesKill(_ context.Context, _ e2bgen.PostAdminTeamsTeamIDSandboxesKillRequestObject) (e2bgen.PostAdminTeamsTeamIDSandboxesKillResponseObject, error) {
	return unsupportedOp("PostAdminTeamsTeamIDSandboxesKill", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) GetNodes(_ context.Context, _ e2bgen.GetNodesRequestObject) (e2bgen.GetNodesResponseObject, error) {
	return unsupportedOp("GetNodes", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) GetNodesNodeID(_ context.Context, _ e2bgen.GetNodesNodeIDRequestObject) (e2bgen.GetNodesNodeIDResponseObject, error) {
	return unsupportedOp("GetNodesNodeID", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) PostNodesNodeID(_ context.Context, _ e2bgen.PostNodesNodeIDRequestObject) (e2bgen.PostNodesNodeIDResponseObject, error) {
	return unsupportedOp("PostNodesNodeID", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) GetSnapshots(_ context.Context, _ e2bgen.GetSnapshotsRequestObject) (e2bgen.GetSnapshotsResponseObject, error) {
	return unsupportedOp("GetSnapshots", catArchitectural, msgSnapshots), nil
}

func (s *Server) GetTeams(_ context.Context, _ e2bgen.GetTeamsRequestObject) (e2bgen.GetTeamsResponseObject, error) {
	return unsupportedOp("GetTeams", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) GetTeamsTeamIDMetrics(_ context.Context, _ e2bgen.GetTeamsTeamIDMetricsRequestObject) (e2bgen.GetTeamsTeamIDMetricsResponseObject, error) {
	return unsupportedOp("GetTeamsTeamIDMetrics", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) GetTeamsTeamIDMetricsMax(_ context.Context, _ e2bgen.GetTeamsTeamIDMetricsMaxRequestObject) (e2bgen.GetTeamsTeamIDMetricsMaxResponseObject, error) {
	return unsupportedOp("GetTeamsTeamIDMetricsMax", catArchitectural, msgClusterAdmin), nil
}

func (s *Server) PostTemplates(_ context.Context, _ e2bgen.PostTemplatesRequestObject) (e2bgen.PostTemplatesResponseObject, error) {
	return unsupportedOp("PostTemplates", catPlatform, msgTemplateBuild), nil
}

func (s *Server) GetTemplatesAliasesAlias(_ context.Context, _ e2bgen.GetTemplatesAliasesAliasRequestObject) (e2bgen.GetTemplatesAliasesAliasResponseObject, error) {
	return unsupportedOp("GetTemplatesAliasesAlias", catUnimplemented, msgTemplateAlias), nil
}

func (s *Server) DeleteTemplatesTags(_ context.Context, _ e2bgen.DeleteTemplatesTagsRequestObject) (e2bgen.DeleteTemplatesTagsResponseObject, error) {
	return unsupportedOp("DeleteTemplatesTags", catPlatform, msgTemplateTags), nil
}

func (s *Server) PostTemplatesTags(_ context.Context, _ e2bgen.PostTemplatesTagsRequestObject) (e2bgen.PostTemplatesTagsResponseObject, error) {
	return unsupportedOp("PostTemplatesTags", catPlatform, msgTemplateTags), nil
}

func (s *Server) DeleteTemplatesTemplateID(_ context.Context, _ e2bgen.DeleteTemplatesTemplateIDRequestObject) (e2bgen.DeleteTemplatesTemplateIDResponseObject, error) {
	return unsupportedOp("DeleteTemplatesTemplateID", catPlatform, msgTemplateBuild), nil
}

func (s *Server) PatchTemplatesTemplateID(_ context.Context, _ e2bgen.PatchTemplatesTemplateIDRequestObject) (e2bgen.PatchTemplatesTemplateIDResponseObject, error) {
	return unsupportedOp("PatchTemplatesTemplateID", catPlatform, msgTemplateBuild), nil
}

func (s *Server) PostTemplatesTemplateID(_ context.Context, _ e2bgen.PostTemplatesTemplateIDRequestObject) (e2bgen.PostTemplatesTemplateIDResponseObject, error) {
	return unsupportedOp("PostTemplatesTemplateID", catPlatform, msgTemplateBuild), nil
}

func (s *Server) PostTemplatesTemplateIDBuildsBuildID(_ context.Context, _ e2bgen.PostTemplatesTemplateIDBuildsBuildIDRequestObject) (e2bgen.PostTemplatesTemplateIDBuildsBuildIDResponseObject, error) {
	return unsupportedOp("PostTemplatesTemplateIDBuildsBuildID", catPlatform, msgTemplateBuild), nil
}

func (s *Server) GetTemplatesTemplateIDBuildsBuildIDLogs(_ context.Context, _ e2bgen.GetTemplatesTemplateIDBuildsBuildIDLogsRequestObject) (e2bgen.GetTemplatesTemplateIDBuildsBuildIDLogsResponseObject, error) {
	return unsupportedOp("GetTemplatesTemplateIDBuildsBuildIDLogs", catPlatform, msgTemplateBuild), nil
}

func (s *Server) GetTemplatesTemplateIDBuildsBuildIDStatus(_ context.Context, _ e2bgen.GetTemplatesTemplateIDBuildsBuildIDStatusRequestObject) (e2bgen.GetTemplatesTemplateIDBuildsBuildIDStatusResponseObject, error) {
	return unsupportedOp("GetTemplatesTemplateIDBuildsBuildIDStatus", catPlatform, msgTemplateBuild), nil
}

func (s *Server) GetTemplatesTemplateIDFilesHash(_ context.Context, _ e2bgen.GetTemplatesTemplateIDFilesHashRequestObject) (e2bgen.GetTemplatesTemplateIDFilesHashResponseObject, error) {
	return unsupportedOp("GetTemplatesTemplateIDFilesHash", catPlatform, msgTemplateBuild), nil
}

func (s *Server) GetTemplatesTemplateIDTags(_ context.Context, _ e2bgen.GetTemplatesTemplateIDTagsRequestObject) (e2bgen.GetTemplatesTemplateIDTagsResponseObject, error) {
	return unsupportedOp("GetTemplatesTemplateIDTags", catPlatform, msgTemplateTags), nil
}

// GetV2Sandboxes is the paginated list endpoint the current E2B SDK targets
// (GET /v2/sandboxes). It applies the same namespace/team/user scoping as the
// legacy GetSandboxes, then filters by the optional metadata/state query params
// and returns one page. The next-page cursor is returned via the "x-next-token"
// response header — the SDK paginator reads it there and stops once it is absent.
func (s *Server) GetV2Sandboxes(ctx context.Context, req e2bgen.GetV2SandboxesRequestObject) (e2bgen.GetV2SandboxesResponseObject, error) {
	auth := authFrom(ctx)
	result, appErr := s.sandbox.List(ctx, service.SandboxListFilter{
		Namespace: auth.Namespace,
		Team:      auth.Team,
		User:      auth.User,
		Limit:     0,
	})
	if appErr != nil {
		return e2bgen.GetV2Sandboxes500JSONResponse{N500JSONResponse: e2bgen.N500JSONResponse(errRespAppErr(ctx, appErr))}, nil
	}

	metaFilter, err := parseMetadataFilter(req.Params.Metadata)
	if err != nil {
		return e2bgen.GetV2Sandboxes400JSONResponse{N400JSONResponse: e2bgen.N400JSONResponse(errRespCode(400, "invalid metadata filter"))}, nil
	}
	stateFilter := newStateFilter(req.Params.State)

	poolMap := s.loadPoolMap(ctx, auth.Namespace)

	items := make([]e2bgen.ListedSandbox, 0, len(result.Items))
	for i := range result.Items {
		sb := &result.Items[i]
		if !e2bdomain.IsLive(sb) {
			continue
		}
		listed := domainSandboxToListedSandbox(sb, poolMap[sb.PoolName])
		if !stateFilter.matches(listed.State) {
			continue
		}
		if !metadataMatches(listed.Metadata, metaFilter) {
			continue
		}
		items = append(items, listed)
	}

	// X-Total-Running counts sandboxes matching the filters before pagination.
	running := 0
	for i := range items {
		if items[i].State == e2bgen.Running {
			running++
		}
	}

	offset := min(decodeNextToken(req.Params.NextToken), len(items))
	end := len(items)
	if req.Params.Limit != nil && *req.Params.Limit > 0 {
		end = min(offset+int(*req.Params.Limit), end)
	}

	nextToken := ""
	if end < len(items) {
		nextToken = encodeNextToken(end)
	}

	return e2bgen.GetV2Sandboxes200JSONResponse{
		Body: items[offset:end],
		Headers: e2bgen.GetV2Sandboxes200ResponseHeaders{
			XNextToken:    nextToken,
			XTotalRunning: int32(running),
		},
	}, nil
}

// parseMetadataFilter decodes the E2B "metadata" query param — a URL-encoded
// "key=value&key2=value2" string — into a map. A sandbox matches only when every
// pair is present (AND semantics), mirroring the upstream E2B filter.
func parseMetadataFilter(raw *string) (map[string]string, error) {
	if raw == nil || *raw == "" {
		return nil, nil
	}
	values, err := url.ParseQuery(*raw)
	if err != nil {
		return nil, err
	}
	out := make(map[string]string, len(values))
	for k, v := range values {
		if len(v) > 0 {
			out[k] = v[0]
		}
	}
	return out, nil
}

func metadataMatches(meta *e2bgen.SandboxMetadata, filter map[string]string) bool {
	if len(filter) == 0 {
		return true
	}
	if meta == nil {
		return false
	}
	for k, v := range filter {
		if (*meta)[k] != v {
			return false
		}
	}
	return true
}

// stateFilter is the parsed set of sandbox states requested via the "state"
// query param. A nil/empty set matches every state.
type stateFilter map[e2bgen.SandboxState]struct{}

func newStateFilter(states *[]e2bgen.SandboxState) stateFilter {
	if states == nil || len(*states) == 0 {
		return nil
	}
	set := make(stateFilter, len(*states))
	for _, st := range *states {
		set[st] = struct{}{}
	}
	return set
}

func (f stateFilter) matches(state e2bgen.SandboxState) bool {
	if len(f) == 0 {
		return true
	}
	_, ok := f[state]
	return ok
}

// encodeNextToken / decodeNextToken carry an opaque offset cursor. The offset is
// base64-encoded so callers treat it as opaque; a malformed token decodes to 0.
func encodeNextToken(offset int) string {
	return base64.RawURLEncoding.EncodeToString([]byte(strconv.Itoa(offset)))
}

func decodeNextToken(token *string) int {
	if token == nil || *token == "" {
		return 0
	}
	raw, err := base64.RawURLEncoding.DecodeString(*token)
	if err != nil {
		return 0
	}
	n, err := strconv.Atoi(string(raw))
	if err != nil || n < 0 {
		return 0
	}
	return n
}

func (s *Server) PostV2Templates(_ context.Context, _ e2bgen.PostV2TemplatesRequestObject) (e2bgen.PostV2TemplatesResponseObject, error) {
	return unsupportedOp("PostV2Templates", catPlatform, msgTemplateBuild), nil
}

func (s *Server) PatchV2TemplatesTemplateID(_ context.Context, _ e2bgen.PatchV2TemplatesTemplateIDRequestObject) (e2bgen.PatchV2TemplatesTemplateIDResponseObject, error) {
	return unsupportedOp("PatchV2TemplatesTemplateID", catPlatform, msgTemplateBuild), nil
}

func (s *Server) PostV2TemplatesTemplateIDBuildsBuildID(_ context.Context, _ e2bgen.PostV2TemplatesTemplateIDBuildsBuildIDRequestObject) (e2bgen.PostV2TemplatesTemplateIDBuildsBuildIDResponseObject, error) {
	return unsupportedOp("PostV2TemplatesTemplateIDBuildsBuildID", catPlatform, msgTemplateBuild), nil
}

func (s *Server) PostV3Templates(_ context.Context, _ e2bgen.PostV3TemplatesRequestObject) (e2bgen.PostV3TemplatesResponseObject, error) {
	return unsupportedOp("PostV3Templates", catPlatform, msgTemplateBuild), nil
}

func (s *Server) GetVolumes(_ context.Context, _ e2bgen.GetVolumesRequestObject) (e2bgen.GetVolumesResponseObject, error) {
	return unsupportedOp("GetVolumes", catArchitectural, msgVolumes), nil
}

func (s *Server) PostVolumes(_ context.Context, _ e2bgen.PostVolumesRequestObject) (e2bgen.PostVolumesResponseObject, error) {
	return unsupportedOp("PostVolumes", catArchitectural, msgVolumes), nil
}

func (s *Server) DeleteVolumesVolumeID(_ context.Context, _ e2bgen.DeleteVolumesVolumeIDRequestObject) (e2bgen.DeleteVolumesVolumeIDResponseObject, error) {
	return unsupportedOp("DeleteVolumesVolumeID", catArchitectural, msgVolumes), nil
}

func (s *Server) GetVolumesVolumeID(_ context.Context, _ e2bgen.GetVolumesVolumeIDRequestObject) (e2bgen.GetVolumesVolumeIDResponseObject, error) {
	return unsupportedOp("GetVolumesVolumeID", catArchitectural, msgVolumes), nil
}
