/**
 * Copyright 2026 ScitiX
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The surfaces content sits on, as class recipes in one place.
 *
 * These are strings rather than components on purpose: the shapes they describe
 * are applied to whatever element already exists at the call site — a `div`, a
 * shadcn `Card`, a `dl` — and wrapping each of those in a component would add a
 * node to the tree for nothing. `components/ui/` stays untouched (it is
 * regenerated by shadcn), so the app-level look is expressed here instead.
 *
 * The radius ramp they use is the one `app/globals.css` documents off the 9px
 * `--radius` base:
 *
 *   panel / card / table frame   rounded-xl   12.6px
 *   sub-panel, info row          rounded-lg    9px
 *   chip, control                rounded-md    7.2px
 *
 * Reach for a token here before writing `border` + `bg-*` by hand; the reason
 * these exist is that the same block was written twenty-five different ways.
 */

/**
 * A block of content floating on the page canvas.
 *
 * No drop shadow: the canvas is a shade below the panel, so a resting panel is
 * already legible against it and a shadow would claim it floats when it does
 * not. The edge is a `ring` rather than a `border` so it costs no layout box —
 * a bordered panel is 2px wider than its content, which shows up as misalignment
 * when a panel sits beside one that is not bordered.
 */
export const panelSurface = "bg-card rounded-xl shadow-none ring-1 ring-border"

/**
 * The frame a data grid mounts in. Contributes no padding — the grid's own
 * cells own that — and clips, so the grid's corners follow the panel's radius.
 *
 * `overflow-hidden` is load-bearing twice over: it rounds the header band and
 * the last row, and it is what the scroll area inside already relies on.
 */
export const gridPanel = `${panelSurface} overflow-hidden p-0`

/**
 * The recessed row that dialogs and detail panes use to quote a value back at
 * the reader — the name of the thing about to be deleted, a key's fingerprint,
 * a request id.
 *
 * A `border` here rather than a ring: these sit inside a dialog's flow where the
 * extra 2px is what separates them from the copy above, not a misalignment.
 */
export const infoRow = "border-border bg-secondary rounded-lg border"
