// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "concepts/autoscaling.mdx": () => import("../content/docs/concepts/autoscaling.mdx?collection=docs"), "concepts/cross-cluster.mdx": () => import("../content/docs/concepts/cross-cluster.mdx?collection=docs"), "concepts/egress-and-secrets.mdx": () => import("../content/docs/concepts/egress-and-secrets.mdx?collection=docs"), "concepts/envs.mdx": () => import("../content/docs/concepts/envs.mdx?collection=docs"), "concepts/index.mdx": () => import("../content/docs/concepts/index.mdx?collection=docs"), "concepts/inplace-update.mdx": () => import("../content/docs/concepts/inplace-update.mdx?collection=docs"), "concepts/pools.mdx": () => import("../content/docs/concepts/pools.mdx?collection=docs"), "concepts/templates.mdx": () => import("../content/docs/concepts/templates.mdx?collection=docs"), "tutorials/cli.mdx": () => import("../content/docs/tutorials/cli.mdx?collection=docs"), "tutorials/e2b.mdx": () => import("../content/docs/tutorials/e2b.mdx?collection=docs"), "tutorials/mini-swe-agent.mdx": () => import("../content/docs/tutorials/mini-swe-agent.mdx?collection=docs"), "concepts/skills/abx-common.mdx": () => import("../content/docs/concepts/skills/abx-common.mdx?collection=docs"), "concepts/skills/abx-harbor-framework.mdx": () => import("../content/docs/concepts/skills/abx-harbor-framework.mdx?collection=docs"), "concepts/skills/abx-managed-agent.mdx": () => import("../content/docs/concepts/skills/abx-managed-agent.mdx?collection=docs"), "concepts/skills/abx-observe.mdx": () => import("../content/docs/concepts/skills/abx-observe.mdx?collection=docs"), "concepts/skills/abx-reinforcement-learning.mdx": () => import("../content/docs/concepts/skills/abx-reinforcement-learning.mdx?collection=docs"), "concepts/skills/abx-resource-capacity.mdx": () => import("../content/docs/concepts/skills/abx-resource-capacity.mdx?collection=docs"), "concepts/skills/abx-sandbox-docker.mdx": () => import("../content/docs/concepts/skills/abx-sandbox-docker.mdx?collection=docs"), "concepts/skills/abx-sandbox-network.mdx": () => import("../content/docs/concepts/skills/abx-sandbox-network.mdx?collection=docs"), "concepts/skills/abx-sandbox-secrets.mdx": () => import("../content/docs/concepts/skills/abx-sandbox-secrets.mdx?collection=docs"), "concepts/skills/index.mdx": () => import("../content/docs/concepts/skills/index.mdx?collection=docs"), }),
};
export default browserCollections;