/**
 * Copyright 2026 ScitiX
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sandbox-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List global sandbox templates
         * @description Returns all SandboxTemplate resources on the Master cluster.
         *     Admin callers see all templates; tenant callers see only templates
         *     accessible within their team/user scope.
         */
        get: operations["ListSandboxTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sandbox-templates/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SandboxTemplate name (RFC 1123 DNS label). */
                name: string;
            };
            cookie?: never;
        };
        /** Get a global sandbox template */
        get: operations["GetSandboxTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sandbox-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a global sandbox template (admin)
         * @description Creates a SandboxTemplate on the Master cluster and broadcasts it to all
         *     connected Worker clusters. Requires admin role.
         */
        post: operations["AdminCreateSandboxTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/sandbox-templates/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SandboxTemplate name (RFC 1123 DNS label). */
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Update a global sandbox template (admin)
         * @description Replaces a SandboxTemplate on the Master cluster and broadcasts the update
         *     to all connected Worker clusters. Requires admin role.
         */
        put: operations["AdminUpdateSandboxTemplate"];
        post?: never;
        /**
         * Delete a global sandbox template (admin)
         * @description Deletes a SandboxTemplate from the Master cluster and broadcasts the deletion
         *     to all connected Worker clusters. Requires admin role.
         */
        delete: operations["AdminDeleteSandboxTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys for the authenticated user
         * @description Returns keys scoped to the caller's team/user from the JWT.
         */
        get: operations["ListMyApiKeys"];
        put?: never;
        /**
         * Create an API key
         * @description Creates an API key. The user/team/namespace are derived from the JWT unless
         *     admin impersonation headers are provided.
         */
        post: operations["CreateApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID (agentbox-apikey-<hash-prefix>). */
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an API key */
        delete: operations["DeleteApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images-catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List image datasets */
        get: operations["ListImagesCatalog"];
        put?: never;
        /** Create or upsert an image dataset (admin) */
        post: operations["CreateImageDataset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/images-catalog/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dataset ID. */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /** Update an image dataset (admin) */
        put: operations["UpdateImageDataset"];
        post?: never;
        /** Delete an image dataset (admin) */
        delete: operations["DeleteImageDataset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SandboxTemplate: {
            /** @description Name of the SandboxTemplate cluster resource (RFC 1123 DNS label). */
            name: string;
            /** @description User-defined version of this template (from spec.version). */
            version?: string;
            /** @description Human-readable description of the template (from spec.description). */
            description?: string;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp when the template was created.
             */
            createdAt?: string;
            /** @description CPU resource quantity derived from the template's pod spec (e.g. "1", "100m"). */
            cpu?: string;
            /** @description Memory resource quantity derived from the template's pod spec (e.g. "16Gi", "512Mi"). */
            memory?: string;
            /** @description Resource origin: 'global' (synced via ws-proxy) or 'local' (created directly on worker). Empty for legacy resources. */
            syncSource?: string;
            /**
             * @description Markdown documentation for the template, stored in the agentbox.navix.sh/docs annotation.
             *     Supports the placeholders listed under SandboxEnv.envDocs. On Template Get the env-scoped
             *     ones become readable hints (YOUR_ENV_NAME, YOUR_POOL_NAME, YOUR_API_KEY) because there is
             *     no env context, while everything derived from the serving cluster's config
             *     (${AGBX_CLUSTER_ID}, the gateway URLs, ${AGBX_HOST}, ${AGBX_INNER_IP}, ${AGBX_HTTPS},
             *     ${AGBX_REGISTRY_HOST}) is substituted for real; GetSandboxEnv substitutes everything.
             *
             *     Editing only the docs does not require bumping spec.version — docs never reach the
             *     rendered Pod, so they name no new template revision.
             */
            docs?: string;
            /** @description Complete raw SandboxTemplate CRD YAML (without managedFields). Includes resourceVersion and uid for optimistic locking on PUT. */
            crdYaml?: string;
        };
        /** @description Lightweight summary returned by the List endpoint — omits spec, specYaml, labels, annotations, status, and full docs to reduce payload size. */
        SandboxTemplateSummary: {
            /** @description Name of the SandboxTemplate cluster resource (RFC 1123 DNS label). */
            name: string;
            /** @description User-defined version of this template (from spec.version). */
            version?: string;
            /** @description Human-readable description of the template (from spec.description). */
            description?: string;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp when the template was created.
             */
            createdAt?: string;
            /** @description CPU resource quantity derived from the template's pod spec (e.g. "1", "100m"). */
            cpu?: string;
            /** @description Memory resource quantity derived from the template's pod spec (e.g. "16Gi", "512Mi"). */
            memory?: string;
            /** @description Resource origin: 'global' (synced via ws-proxy) or 'local' (created directly on worker). */
            syncSource?: string;
            /** @description List of runtime endpoint names defined in this template (lightweight alternative to the full Runtime objects). */
            runtimeNames?: string[];
            /** @description True when the template has documentation in the agentbox.navix.sh/docs annotation. */
            hasDocs?: boolean;
        };
        SandboxTemplateEnvelope: {
            template: components["schemas"]["SandboxTemplate"];
        };
        ListSandboxTemplatesResult: {
            /** @description Page of SandboxTemplateSummary objects (lightweight — use GET /sandbox-templates/{name} for full details). */
            items: components["schemas"]["SandboxTemplateSummary"][];
            /** @description Total number of templates (before pagination). */
            total: number;
            /** @description Maximum number of items requested per page. */
            limit: number;
            /** @description Number of items skipped before this page. */
            offset: number;
        };
        UpsertSandboxTemplateRequest: {
            /** @description Complete SandboxTemplate CRD object serialized as JSON. metadata.name is required. Labels, annotations, and resourceVersion are extracted from the JSON. */
            crdJson: string;
        };
        /**
         * @description Standard error envelope. Individual endpoints override the `example` per response
         *     code so the shape of `detail` is accurate for that specific failure mode.
         */
        ErrorResponse: {
            /** @description Human-readable error message. */
            error: string;
            /**
             * @description Machine-readable business error code. Only present for specific business errors
             *     that require special handling (e.g. `API_KEY_REQUIRED` prompts the client to
             *     call `POST /api-keys` before retrying). Generic HTTP errors (400, 500, etc.) do
             *     NOT carry this field.
             * @example API_KEY_REQUIRED
             */
            errorCode?: string;
            /**
             * @description Structured context for the error. Shape depends on the failure mode. Common
             *     variants:
             *       * Plain string — simple context ("pool not found: my-pool")
             *       * `PoolStatusDetail` — returned on 409/429 from CreateSandbox to describe
             *         pool replica breakdown and retry hints
             *       * `{availablePools: [...]}` — returned on 404 from CreateSandbox / 400 from
             *         CreateSandboxPool when the referenced resource does not exist
             *       * `{availableTemplates: [...]}` — returned on 400 from CreateSandboxPool
             *       * `{availableQuotaURLs: [...]}` — returned on 400 when spec.reservation is
             *         set but quotaURL is missing
             */
            detail?: unknown;
        };
        APIKeyItem: {
            /** @description Unique identifier for this API key. */
            keyId: string;
            /** @description Username associated with the key. */
            user?: string;
            /** @description Team associated with the key. */
            team?: string;
            /** @description Role granted by this key (e.g. tenant, admin). */
            role: string;
            /** @description Human-readable description of the key. */
            description?: string;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp when the key was created.
             */
            issuedAt: string;
            /**
             * Format: date-time
             * @description RFC 3339 expiry timestamp, or absent if the key never expires.
             */
            expiresAt?: string;
            /** @description Resource origin: 'global' (synced via ws-proxy) or 'local' (created directly on worker). Empty for legacy resources. */
            syncSource?: string;
            /** @description The full raw API key value (agbx_...), present only for keys created after plaintext storage was introduced. Absent for legacy keys. Displayed masked in UI; the full value is returned here for recovery by authorised callers. */
            rawToken?: string;
        };
        CreateAPIKeyResult: {
            /** @description The raw API key value (only returned once at creation time; store it securely). */
            apiKey: string;
            /** @description Unique identifier for this API key (used to look up or delete the key). */
            keyId: string;
            /** @description Username associated with the key. */
            user?: string;
            /** @description Team associated with the key. */
            team?: string;
            /** @description Role granted by this key (e.g. tenant, admin). */
            role: string;
            /** @description Human-readable description of the key. */
            description?: string;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp when the key was created.
             */
            issuedAt: string;
            /**
             * Format: date-time
             * @description RFC 3339 expiry timestamp, or absent if the key never expires.
             */
            expiresAt?: string;
        };
        /** @description List of API key objects. Returned in full — the endpoint does not paginate. */
        ListAPIKeysResult: components["schemas"]["APIKeyItem"][];
        CreateAPIKeyRequest: {
            description?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @description Import mode: pre-computed token hash. */
            tokenHash?: string;
            /** @description Import mode: hash prefix (8 hex chars). */
            hashPrefix?: string;
            /**
             * Format: date-time
             * @description Import mode: original issuedAt timestamp.
             */
            issuedAt?: string;
            /** @description Import mode: original namespace. */
            namespace?: string;
            /** @description Import mode: original user. */
            user?: string;
            /** @description Import mode: original team. */
            team?: string;
        };
        ImageDataset: {
            id: string;
            name: string;
            description?: string;
            imageCount?: number;
            category?: string;
            source?: string;
            huggingFaceUrl?: string;
            tags?: string[];
            clusterDocs?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ListSandboxTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSandboxTemplatesResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetSandboxTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SandboxTemplate name (RFC 1123 DNS label). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxTemplateEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminCreateSandboxTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertSandboxTemplateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxTemplateEnvelope"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminUpdateSandboxTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SandboxTemplate name (RFC 1123 DNS label). */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertSandboxTemplateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SandboxTemplateEnvelope"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    AdminDeleteSandboxTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description SandboxTemplate name (RFC 1123 DNS label). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListMyApiKeys: {
        parameters: {
            query?: {
                /** @description Filter by team (admin only). */
                team?: string;
                /** @description Filter by user (admin only). */
                user?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAPIKeysResult"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateApiKey: {
        parameters: {
            query?: never;
            header?: {
                /** @description Admin only: create key on behalf of this team. */
                "X-Impersonate-Team"?: string;
                /** @description Admin only: create key on behalf of this user. */
                "X-Impersonate-User"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPIKeyRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAPIKeyResult"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict (max keys per user exceeded) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID (agentbox-apikey-<hash-prefix>). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListImagesCatalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDataset"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateImageDataset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageDataset"];
            };
        };
        responses: {
            /** @description Updated (upsert) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDataset"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDataset"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    UpdateImageDataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dataset ID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageDataset"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDataset"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    DeleteImageDataset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dataset ID. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
