apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-sandbox-hub.proxyFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-sandbox-hub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "agent-sandbox-hub.proxySelectorLabels" . | nindent 4 }}
  ports:
    - name: ws
      port: 9003
      targetPort: 9003
      protocol: TCP
    - name: internal
      port: 9004
      targetPort: 9004
      protocol: TCP
