#!/usr/bin/env python3
"""
generate-helm.py — Sync controller-gen artifacts into Helm charts.

Run from the repository root:
    python3 hack/scripts/generate-helm.py
    (or via `make sync-crds-to-helm`)

What it does:
  1. CRDs (config/crd/bases/*.yaml)
       → installer/helm/agent-sandbox-worker/crds/   (all CRDs)
       → installer/helm/agent-sandbox-hub/crds/       (SandboxTemplate only)
     Injects `helm.sh/resource-policy: keep` so `helm uninstall` never
     removes the CRDs.

  2. manager ClusterRole (config/rbac/role.yaml)
       → installer/helm/agent-sandbox-worker/templates/rbac-manager-role.yaml
     The generated `rules:` block is wrapped in a Helm-templated ClusterRole
     using the release fullname as a prefix.  The output file carries a
     DO-NOT-EDIT header; run this script (or `make sync-crds-to-helm`) to
     regenerate it.
"""

import sys
import textwrap
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("ERROR: PyYAML not found. Install it with: pip install pyyaml")

REPO_ROOT = Path(__file__).resolve().parents[2]

CRD_SRC = REPO_ROOT / "config" / "crd" / "bases"
RBAC_SRC = REPO_ROOT / "config" / "rbac" / "role.yaml"

WORKER_CRD_DST = REPO_ROOT / "installer" / "helm" / "agent-sandbox-worker" / "crds"
HUB_CRD_DST    = REPO_ROOT / "installer" / "helm" / "agent-sandbox-hub"    / "crds"
MANAGER_ROLE_DST = (
    REPO_ROOT
    / "installer" / "helm" / "agent-sandbox-worker"
    / "templates" / "rbac-manager-role.yaml"
)

HELM_RESOURCE_POLICY_ANNOTATION = "helm.sh/resource-policy: keep"


def inject_keep_annotation(doc: dict) -> dict:
    """Add helm.sh/resource-policy: keep to metadata.annotations."""
    meta = doc.setdefault("metadata", {})
    annotations = meta.setdefault("annotations", {})
    annotations["helm.sh/resource-policy"] = "keep"
    return doc


def sync_crds() -> None:
    if not CRD_SRC.is_dir():
        sys.exit(f"ERROR: '{CRD_SRC}' not found. Run from the repo root.")

    crd_files = sorted(CRD_SRC.glob("*.yaml"))
    if not crd_files:
        print(f"  WARNING: no CRD files found in {CRD_SRC}")
        return

    print("==> agent-sandbox-worker (all CRDs)")
    WORKER_CRD_DST.mkdir(parents=True, exist_ok=True)
    for src in crd_files:
        dst = WORKER_CRD_DST / src.name
        doc = yaml.safe_load(src.read_text())
        inject_keep_annotation(doc)
        dst.write_text(yaml.dump(doc, default_flow_style=False, sort_keys=False))
        print(f"  {src.relative_to(REPO_ROOT)} -> {dst.relative_to(REPO_ROOT)}")

    print("==> agent-sandbox-hub (SandboxTemplate only)")
    HUB_CRD_DST.mkdir(parents=True, exist_ok=True)
    for src in crd_files:
        if "sandboxtemplates" not in src.name:
            continue
        dst = HUB_CRD_DST / src.name
        doc = yaml.safe_load(src.read_text())
        inject_keep_annotation(doc)
        dst.write_text(yaml.dump(doc, default_flow_style=False, sort_keys=False))
        print(f"  {src.relative_to(REPO_ROOT)} -> {dst.relative_to(REPO_ROOT)}")


def sync_manager_role() -> None:
    print("==> agent-sandbox-worker manager ClusterRole")

    if not RBAC_SRC.is_file():
        print(
            f"  WARNING: '{RBAC_SRC}' not found; skipping RBAC sync. "
            "Run 'make manifests' first.",
            file=sys.stderr,
        )
        return

    role = yaml.safe_load(RBAC_SRC.read_text())
    rules = role.get("rules", [])

    # Render rules back to YAML, indented by 2 spaces so it reads naturally
    # inside the ClusterRole body.
    rules_yaml = yaml.dump({"rules": rules}, default_flow_style=False, sort_keys=False)
    # yaml.dump always adds a trailing newline; strip it so we can control spacing.
    rules_yaml = rules_yaml.rstrip("\n")

    helm_template = textwrap.dedent("""\
        {{/*
          rbac-manager-role.yaml — AUTO-GENERATED by hack/scripts/generate-helm.py
          Do NOT edit manually. Run `make sync-crds-to-helm` to regenerate.
          Source: config/rbac/role.yaml (produced by `make manifests`)
        */}}
        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: {{ include "agent-sandbox-worker.fullname" . }}-manager-role
          labels:
            {{- include "agent-sandbox-worker.labels" . | nindent 4 }}
        """)

    MANAGER_ROLE_DST.parent.mkdir(parents=True, exist_ok=True)
    MANAGER_ROLE_DST.write_text(helm_template + rules_yaml + "\n")
    print(
        f"  {RBAC_SRC.relative_to(REPO_ROOT)} -> "
        f"{MANAGER_ROLE_DST.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    sync_crds()
    sync_manager_role()
    print("Done.")
