#!/usr/bin/env python3
# Copyright 2026 ScitiX
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
generate-helm.py — Sync controller-gen artifacts into Helm charts.

Run from the repository root:
    python3 hack/scripts/generate-helm.py
    (or via `make sync-crds-to-helm`)

What it does:
  1. CRDs (config/crd/bases/*.yaml)
       → installer/helm/agent-sandbox-worker/templates/crds/   (all CRDs)
       → installer/helm/agent-sandbox-hub/templates/crds/      (SandboxTemplate only)
     Each emitted file is wrapped in `{{- if .Values.crds.create }} ... {{- end }}`
     so users can opt out, and carries `helm.sh/resource-policy: keep` so the
     CRDs survive `helm uninstall`. Placing them under `templates/` (rather
     than the chart-root `crds/` directory) lets `helm upgrade` actually
     update CRD schemas — the chart-root `crds/` directory is install-only.

  2. manager ClusterRole (config/rbac/role.yaml)
       → installer/helm/agent-sandbox-worker/templates/rbac-manager-role.yaml
     The generated `rules:` block is wrapped in a Helm-templated ClusterRole
     using the release fullname as a prefix.  The output file carries a
     DO-NOT-EDIT header; run this script (or `make sync-crds-to-helm`) to
     regenerate it.
"""

import shutil
import sys
import textwrap
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("ERROR: PyYAML not found. Install it with: pip install pyyaml")

REPO_ROOT = Path(__file__).resolve().parents[2]

CRD_SRC = REPO_ROOT / "config" / "crd" / "bases"
RBAC_SRC = REPO_ROOT / "config" / "rbac" / "role.yaml"

WORKER_CRD_DST = (
    REPO_ROOT / "installer" / "helm" / "agent-sandbox-worker" / "templates" / "crds"
)
HUB_CRD_DST = (
    REPO_ROOT / "installer" / "helm" / "agent-sandbox-hub" / "templates" / "crds"
)
MANAGER_ROLE_DST = (
    REPO_ROOT
    / "installer" / "helm" / "agent-sandbox-worker"
    / "templates" / "rbac-manager-role.yaml"
)

HELM_RESOURCE_POLICY_ANNOTATION = "helm.sh/resource-policy: keep"

#
# Header comments are placed INSIDE the `{{- if }}` guard so that, when
# `crds.create=false`, the template renders to nothing instead of a
# comment-only YAML document. A standalone comment-only document parses to
# `null` and breaks downstream tooling that does
# `obj.(*unstructured.Unstructured)` on every document in the manifest.
#
# We also intentionally do NOT emit a `---` separator: Helm already prepends
# `---\n# Source: <chart>/templates/<path>\n` to each rendered template, so
# an extra `---` here would split the output into two documents (comments,
# then CRD body) and reintroduce the phantom-document bug.
CRD_HEADER_TEMPLATE = (
    "{{{{- if .Values.crds.create }}}}\n"
    "# DO NOT EDIT — auto-generated by hack/scripts/generate-helm.py\n"
    "# Source: {src}  (produced by `make manifests`)\n"
    "# Run `make sync-crds-to-helm` to regenerate this file.\n"
)
CRD_FOOTER = "{{- end }}\n"


def inject_keep_annotation(doc: dict) -> dict:
    """Add helm.sh/resource-policy: keep to metadata.annotations."""
    meta = doc.setdefault("metadata", {})
    annotations = meta.setdefault("annotations", {})
    annotations["helm.sh/resource-policy"] = "keep"
    return doc


def write_crd(src: Path, dst_dir: Path, doc: dict) -> Path:
    """Render a CRD doc into a Helm-templated file under dst_dir."""
    rel_src = src.relative_to(REPO_ROOT)
    body = yaml.dump(doc, default_flow_style=False, sort_keys=False)
    dst = dst_dir / src.name
    dst.write_text(CRD_HEADER_TEMPLATE.format(src=rel_src) + body + CRD_FOOTER)
    return dst


def reset_dir(path: Path) -> None:
    """Clear and recreate a directory so deleted CRDs don't linger."""
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True)


def sync_crds() -> None:
    if not CRD_SRC.is_dir():
        sys.exit(f"ERROR: '{CRD_SRC}' not found. Run from the repo root.")

    crd_files = sorted(CRD_SRC.glob("*.yaml"))
    if not crd_files:
        print(f"  WARNING: no CRD files found in {CRD_SRC}")
        return

    print("==> agent-sandbox-worker (all CRDs)")
    reset_dir(WORKER_CRD_DST)
    for src in crd_files:
        doc = yaml.safe_load(src.read_text())
        inject_keep_annotation(doc)
        dst = write_crd(src, WORKER_CRD_DST, doc)
        print(f"  {src.relative_to(REPO_ROOT)} -> {dst.relative_to(REPO_ROOT)}")

    print("==> agent-sandbox-hub (SandboxTemplate only)")
    reset_dir(HUB_CRD_DST)
    for src in crd_files:
        if "sandboxtemplates" not in src.name:
            continue
        doc = yaml.safe_load(src.read_text())
        inject_keep_annotation(doc)
        dst = write_crd(src, HUB_CRD_DST, doc)
        print(f"  {src.relative_to(REPO_ROOT)} -> {dst.relative_to(REPO_ROOT)}")


def sync_manager_role() -> None:
    print("==> agent-sandbox-worker manager ClusterRole")

    if not RBAC_SRC.is_file():
        print(
            f"  WARNING: '{RBAC_SRC}' not found; skipping RBAC sync. "
            "Run 'make manifests' first.",
            file=sys.stderr,
        )
        return

    role = yaml.safe_load(RBAC_SRC.read_text())
    rules = role.get("rules", [])

    # Render rules back to YAML, indented by 2 spaces so it reads naturally
    # inside the ClusterRole body.
    rules_yaml = yaml.dump({"rules": rules}, default_flow_style=False, sort_keys=False)
    # yaml.dump always adds a trailing newline; strip it so we can control spacing.
    rules_yaml = rules_yaml.rstrip("\n")

    helm_template = textwrap.dedent("""\
        {{/*
          rbac-manager-role.yaml — AUTO-GENERATED by hack/scripts/generate-helm.py
          Do NOT edit manually. Run `make sync-crds-to-helm` to regenerate.
          Source: config/rbac/role.yaml (produced by `make manifests`)
        */}}
        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: {{ include "agent-sandbox-worker.fullname" . }}-manager-role
          labels:
            {{- include "agent-sandbox-worker.labels" . | nindent 4 }}
        """)

    MANAGER_ROLE_DST.parent.mkdir(parents=True, exist_ok=True)
    MANAGER_ROLE_DST.write_text(helm_template + rules_yaml + "\n")
    print(
        f"  {RBAC_SRC.relative_to(REPO_ROOT)} -> "
        f"{MANAGER_ROLE_DST.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    sync_crds()
    sync_manager_role()
    print("Done.")
